ex6.rs

Again I didn't add this to the Readme properly as I have no easy way of generating the required Rust playground link. I hope you like the exercise and don't mind adding it to the Readme.

exercise for the ternary operator

---

README.md

Changing the IRC chanel to #rust-beginners

---

tests/tests1.rs

This simply adds a comment on the first tests file that explains how to run tests.  When I went through this originally, I had no idea how to run tests without "cargo test".

Add directions on running tests

---

if/if1.rs

This provides standardize feedback if a solution is correct. Fixes #46.

Create tests for if1.rs

---

ex1.rs

While trying your exercises I noticed that the ex1.rs code is already compiling.

ex1 is compiling

---

macros/macros1.rs
macros/macros2.rs
macros/macros3.rs
macros/macros4.rs

Wanted to make some lessons for macros, since I've seen enough confusion about those. I added some hints; do you think they're good-but-not-direct enough?
I haven't added the examples to the readme, but that should be simple enough. I couldn't get `prlink` to build, though. `>_>`

add macros examples

---

README-template.hbs
README.md

fix dead example link

---

exercises/error_handling/README.md
exercises/functions/REAMDE.md
exercises/if/REAMDE.md
exercises/macros/README.md
exercises/modules/README.md
exercises/move_semantics/README.md
exercises/primitive_types/README.md
exercises/standard_library_types/README.md
exercises/strings/REAMDE.md
exercises/tests/README.md
exercises/threads/README.md
exercises/variables/README.md

Forgot to add changes to last commit of last pr.

Changed Rust Book versions in links to 2018

---

src/run.rs
src/verify.rs

add "--color always" to the other rustc commands

---

src/verify.rs

Add thread exercises to verify entrypoint

---

exercises/standard_library_types/iterators3.rs
info.toml

fix(iterators): Rename iterator3.rs

---

README.md

changing readme image (line 1) to https fixes markdown preview and improves fidelity

etisdew, http to https

---

exercises/structs/README.md

docs: Fix wrong title

---

exercises/standard_library_types/iterators2.rs

A couple of small changes to the `iterators2` exercise. @Jesse-Cameron, it looks like you contributed this exercise, so I wanted to check and see if these changes are in line with your intentions. Happy to adjust if they're not :)

Fix iterators2

---

README.md

Don't see why run should be past tense.  At least in my native General American dialect it shouldn't be.

Tense in README

---

exercises/structs/structs2.rs
info.toml
src/verify.rs

Added one exercise for struct update syntax `struct2.rs`

Added exercise for struct update syntax

---

exercises/test1.rs

closes #194
The author of issue #194 suggests that the wording of the comment is at
least ambiguous about the desired results. I believe this change more
clearly describes the expectation of the exercise.

chore: Clarify comment in exercises/test1.rs

---

src/main.rs

Closes #146
It seems to me that #227 wasn't really fixing the issue.

improvement(watch): clear screen before each `verify()`

---

CONTRIBUTING.md
README.md

Only merge this once we're ready to release 2.0.

chore: Update docs for 2.0

---

exercises/variables/variables5.rs
info.toml

Add variables5 to introduce shadowing

---

exercises/enums/README.md

I jumped in to fix a broken sentence; if there needs to be an associated GH issue please let me know. Thanks.

Fixed mangled sentence from book; edited for clarity

---

exercises/tests/tests1.rs

rustlings "run" command can't use path as parameter now.

chore: Correct test command in tests1.rs comment

---

exercises/traits/traits1.rs
exercises/traits/traits2.rs
info.toml

I hope this doesn't step on any toes but I wanted to try the traits exercises from #216 so I updated them to match the new structure with hints included in info.toml

chore: fixed merge conflicts from traits exercises added by s-marios

---

.gitignore

chore: update gitignore to ignore pdb files

---

exercises/generics/README.md
exercises/generics/generics1.rs
exercises/generics/generics2.rs
exercises/generics/generics3.rs
info.toml

I've added a few exercises on generics since I was looking for some while I was going through rustlings alongside the book. I hope they can be of use (and that generics wasn't a deliberate omission 😄)!

feat: added generics exercises

---

exercises/primitive_types/primitive_types4.rs

fix: revert primitive_types4

---

buildkite.yml

Don't mind me, just testing a CI system that should work

feat(ci): Add buildkite config

---

info.toml

I find myself wanting a hint when doing exercises structs1 and structs2, but there where none. So here is a suggestion for how they could look.

Hints for structs1 and structs2

---

exercises/conversions/from_into.rs
exercises/conversions/from_str.rs
exercises/conversions/try_from_into.rs

Added the missing test case for "from_str" exercise.

test: Add missing test case for from_str exercise

---

exercises/structs/structs3.rs
info.toml

Added a new exercise related to structs, focused around methods implementations.

feat: Added exercise structs3.rs

---

exercises/error_handling/errorsn.rs

I went way off into the weeds on this. Trying harder to stop others.
#387

fix(errorsn): Try harder to confine the user.

---

exercises/generics/generics2.rs

update genercis to exercise to address the point made in #362

fix: update generics2       closes #362

---

exercises/variables/variables3.rs
exercises/variables/variables5.rs

added clarity on line that should not be modified

---

info.toml

Just was updated the book link to add an anchor to have direct access to the "Differences Between Variables and Constants" section that is related to the hint exercise.

chore: Update variables6.rs book link

---

README.md

chore: Fix PowerShell capitalization

---

exercises/traits/README.md

Noticed that the `traits` directory is missing a README.

feat: Add traits README

---

exercises/variables/variables6.rs

Looks like this was cloned from variables5.rs

fix(variables6): minor typo

---

exercises/quiz3.rs

Inconsistent naming when compared with the other quiz files.

fix: fix quiz naming inconsistency

---

info.toml

`rustlings run tests1` wasn't working

fix: rename quiz1 to tests1 in info

---

exercises/standard_library_types/box1.rs

fix(box1): fix comment typo

---

exercises/conversions/as_ref_mut.rs
exercises/conversions/from_into.rs
exercises/conversions/using_as.rs
exercises/generics/generics1.rs
exercises/generics/generics2.rs
exercises/generics/generics3.rs
exercises/primitive_types/primitive_types3.rs
exercises/structs/structs3.rs
exercises/traits/traits1.rs
exercises/traits/traits2.rs

* Add newline after "I AM DONE" in exercises for consistency
* Remove trailing whitespace from exercises

chore: change exercise whitespace for consistency

---

.gitpod.Dockerfile
.gitpod.yml
README.md

We could also add a link to the browser section if the repl.it version gets merged.

feat: Add gitpod support

---

.replit
README.md

How cool is this? One click and go.

feat: Add ability to run rustlings on repl.it

---

exercises/conversions/from_str.rs
exercises/conversions/try_from_into.rs
exercises/conversions/using_as.rs
exercises/enums/enums2.rs
exercises/enums/enums3.rs
exercises/generics/generics1.rs
exercises/generics/generics2.rs
exercises/generics/generics3.rs
exercises/macros/macros4.rs
exercises/standard_library_types/box1.rs
exercises/structs/structs3.rs
exercises/traits/traits2.rs

Similar to #468, these are the changes I ended up with that were not solutions to the exercises but only formatting related, by running rustfmt.

chore: Run rustfmt on exercises

---

exercises/standard_library_types/arc1.rs

fixes a small math error where some indices will get double counted

fix(arc1): index mod should equal thread count

---

exercises/generics/generics3.rs

I actually struggled because I overlooked the fact that I needed to change the 2.1 to "A+". 
So I wanted to make things clearer for future rustlings.

Make comments on example clearer

---

exercises/quiz2.rs

Adding question marks for consistency.
Would it be easier to understand quiz2 ?
Closes#496

fix(exercises): adding question mark to quiz2

---

exercises/standard_library_types/README.md
exercises/standard_library_types/iterators1.rs
info.toml

Hi all, hopefully this exercise would be a gentle but informative intro into iterators.

feat: Added iterators1.rs exercise

---

exercises/tests/tests3.rs
src/verify.rs

Fixing test3 to have enough tests to make sure we test all cases

---

exercises/variables/variables5.rs

fix(variables5) : make shadowing solution more prominent
closes #375

fix(variables5) : make shadowing solution more prominent

---

src/exercise.rs

fix: more unique temp_file

---

src/main.rs

fix: log error output when inotify limit is exceeded

---

exercises/standard_library_types/iterators2.rs

grammar fix in the description

fix(iterators2): Update description

---

src/main.rs

closes #576
I wasn't sure if I wanted to open a PR for this, since I wasn't sure if this was a feature we'd want to add to the project. Opening it up to gain visibility and get more feedback.

feat: Add "rustlings list" feature

---

exercises/threads/threads1.rs

I also ran into difficulty with this exercise. While looking for a hint, I saw this thread issue comment: https://github.com/rust-lang/rustlings/issues/287#issuecomment-644067533
Since `6` is just the appropriate number and has nothing to do with the solution, and since when we're frustrated we have a tendency to grasp at straws, I think it would help a tiny bit to eliminate that possible source of uncertainty.

The magic number 6 is given a bit more context

---

exercises/structs/README.md

references wrong link, confusing

Update Struct README.md

---

exercises/conversions/from_into.rs
exercises/conversions/from_str.rs

:crab: Suggested and resolves #621, add unit test checking trailing comma and some string.

feat(conversions) : add more unit test

---

CONTRIBUTING.md

Modified _Adding an exercise_ section to improve clarity.

Fixed grammar in contributing.md.

---

src/main.rs
tests/integration_tests.rs

Updated `main.rs` to conform to lint `clippy::len_zero`.
Updated `integration_tests.rs` to conform to lint `clippy::expect_fun_call`.

Updated source to follow clippy suggestions.

---

exercises/conversions/from_str.rs

minor/typos: Update from_str.rs

---

src/main.rs

There R spelling errors that need fixing. :smile:

fix: Spelling error

---

exercises/quiz1.rs

Hi,
I was doing these great exercises, but when I did the `quiz1.rs` exercise I actually made a mistake.
I wrote in my `if` statement `amount >= 40` but in the exercise, it says more than 40, so I thought to myself, maybe it would be great to add an extra test to that file that explicitly checks on this.
Another solution could also to change `35` to `40` in the existing test.

chore: Update quiz1.rs add explicit test for 40

---

exercises/variables/variables5.rs

let mut number = 3; can lead to a correct answer, so the comment helps to direct the users to the intended answer.

fix(variables5): confine the answer further

---

README.md

Clone only release tag without history

docs: Faster git clone command

---

info.toml

Added some explanation and links about floating point representation and to use the clippy suggestion. (fixes #390)

chore: clippy1 hint enhancement

---

exercises/standard_library_types/iterators5.rs

Minor formatting improvements in `iterators5.rs`.

chore(iterators5): Minor formatting improvements.

---

exercises/quiz1.rs

add default function name in comment

---

src/main.rs

closes: #842
Took a crack at adding a "quit" command to the `rustlings watch` prompt, as at the moment the only way to exit that shell is to finish all the exercises in one go.
The implementation is a bit clunky... Ideally I would have another channel to signal the intention to quit from the thread spawned by `spawn_watch_shell()`, and the `watch` function would `select` on both receivers, but I don't think there's a way to do that with `std` channels. We can't move to `crossbeam` channels either as the `notify` crate has a hard dependency on `std` channels :( (this is fixed in the upcoming version 5, but it hasn't been released yet...).
I probably should have waited for some discussion on the issue, but it seemed easy enough to give it a shot anyway... Hope this can be useful.

feat: Add "quit" command to `rustlings watch`

---

info.toml

`statemants -> statements`
Thanks for this amazing resource! :)

fix: few spelling mistakes

---

exercises/quiz1.rs

The correct order for doing this quiz should be after "Variables", "Functions", and "If", the last of which is not mentioned in the comments.

fix(quiz1): update to say quiz covers "If"

---

src/exercise.rs

Set clippy::float_cmp lint to deny for clippy1

---

exercises/error_handling/errors1.rs

Signed-off-by: zydxhs <johnsmithcry@163.com>

Add a comment to make the purpose more clearly

---

exercises/intro/README.md
exercises/intro/intro1.rs
exercises/intro/intro2.rs
exercises/variables/variables1.rs
info.toml

The first exercise in the section successfully compiles to acclimate new users to Rustlings and introduce the I AM NOT DONE comment.
The second exercise simply asks the user to complete a Hello World! program.
The intro section is more to introduce Rustlings than to teach Rust.

feat(intro): Proposal to add successfully compiling exercise as the first exercise.

---

README.md

docs: fix some code-blocks were not highlighted

---

exercises/error_handling/errors1.rs

chore: Update test for errors1.rs

---

exercises/standard_library_types/arc1.rs

Functional style is neat and shorter, I think it's good practice to promote it over imperative style.

refactor(arc1): improve readability by using functional style

---

install.sh

Checks for rustup install in install.sh.

---

exercises/README.md

Added missing chapters in the table.

docs: Add missing exercise to book chapter mapping

---

exercises/strings/strings3.rs

fix: make strings3.rs comment wording more clear

---

exercises/traits/traits4.rs

fix(traits4.rs): wrong line number

---

info.toml

fix: Improve hint of lifetimes2

---

exercises/standard_library_types/rc1.rs
info.toml

Adds another smart pointer exercise, since that was requested in the latest release notes. 
It's a fun exercise, very straightforward, to introduce the Rc<T> concept and the API to users who may have not seen it before.

feat: add rc1.rs exercise

---

exercises/options/options1.rs

At 10**AM** and noon, there must be 5 pieces left.

fix(options1): wrong assertions

---

exercises/quiz1.rs

2nd Assert is for greater than or equal to 40, not "more than" like it says in the instructions.

Fix Quiz 1 >= Typo

---

exercises/lifetimes/lifetimes1.rs
exercises/lifetimes/lifetimes2.rs

Adding quotes to make it easier to see what part comes from which string.
Before
`The longest string is long string is long`
After
`The longest string is 'long string is long'`

Add quotes for readability of output

---

exercises/quiz2.rs

Change the comment on quiz2.rs, since there are no hints.

fix(quiz2): fix comment regarding hints

---

info.toml

fix: Fix typo in errors5 hint

---

README.md
flake.lock
flake.nix
shell.nix

This pull request is an attempt to close #683 by adding flake.nix and adding a separate section in the README.

feat: Add flake.nix for nix users

---

.gitpod.yml

update the gitpod extension to use rust-analyzer latest release.

update rust language extension to rust-analyzer

---

src/main.rs

closes #1215 
Small QOL change

Decrease watch delay

---

exercises/quiz2.rs

This sounded off when I read it, perhaps this would be a better way of saying it?

minor grammar tweak for quiz 2

---

exercises/vecs/README.md

docs: add link to docs about `iter_mut` and `map`

---

exercises/vecs/vecs2.rs

Rename iteration var names in vec2.rs for clarity

---

exercises/error_handling/errors2.rs

trivial text correction - description of the total_cost function is wrong: it calculates total cost but instructions say it calculates token count.

correct comments in errors2.rs

---

exercises/hashmaps/hashmaps2.rs

I found hashmaps2.rs quite confusing and did not find it clear what I was supposed to do.
I have seen a few different implementations online and I think they too were not clear on what was required.
I think it would be clearer if we changed it to something like this.

docs:clarify instructions on hashmaps2.rs

---

exercises/hashmaps/README.md
exercises/lifetimes/README.md
exercises/macros/README.md
exercises/options/README.md
exercises/threads/threads1.rs
src/main.rs

Just a little cleanup of some parts where unnecessary trailing spaces remains.

fix: remove trailing spaces

---

info.toml

fix(threads, smart pointers): Swap order of threads and smart pointers exercises

---

exercises/if/if3.rs
info.toml

This highlights on the let assignment syntax with if statements. The error is related to inconsistent primitive types in the arms of the if tree.

added if3 based on: `Using if in a let Statement`

---

exercises/quiz1.rs

`No hints this time` is said twice in a row.

docs: dedup repeated sentence

---

src/exercise.rs
src/main.rs
src/project.rs
src/verify.rs
tests/integration_tests.rs

Some lints are new in the last release :)

Run clippy --fix

---

.envrc
.gitignore

So as to automatically open a nix devShell for those who use direnv/want to use direnv to make their lives more automated.
Ref: #1648

improvement(development): Add nix-direnv integration

---

README.md
exercises/threads/README.md

Very simple README changes. The changeset and commit messages speaks for themselves.

small changes to a few README files

---

exercises/enums/enums3.rs

The TODO comment should be in one line as it's not too long

chore: fix comment in enums3.rs

---

info.toml

Also rewrapped some hints to 80 columns so that they also look good in a terminal.
closes #1698

chore: make hints proper markdown

---

exercises/00_intro/intro1.rs

Very minor typo, but still worth a fix :)

fix(intro1.rs): typo in the exercise body

---

exercises/23_conversions/from_into.rs

I noticed that the comment doesn't exactly fit the addressed line of code, so here is my humble text fix.

chore: update from_into.rs task description to fit the code

---

exercises/23_conversions/from_into.rs

Added a full stop as punctuation.

chore: fixed minor typo

---

src/project.rs

This was a very hard to debug issue when teaching Rust using Rustlings. A student had a whitespace in his path and wasn't able to use rust-analyzer until we finally found out that the path in the `rust-project.json` file wasn't complete.
I also made paths that aren't valid UTF8 fail instead of being replaced silently.

Fix the sysroot path when it contains whitespaces

---

Cargo.lock
Cargo.toml

Remove the home dependency since it is not used

---

Cargo.lock
Cargo.toml
src/main.rs

- Added `shlex` to handle command arguments probably (e.g. `git commit -m "Message with spaces"`)
- Print the help message on an unknown command.
- Recycle the input buffer and lock stdin for a better performance.

Improvements to watch mode

---

README.md

https://github.com/rust-lang/rustlings/issues/1759

fix broken link in windows installation instructions

---

exercises/12_options/options1.rs
src/verify.rs

- `exercises/12_options/options1.rs`: Update instructions grammar.
- `exercises/12_options/options1.rs`: Add test case for zero value.
- `src/verify.rs`: Remove extra white space when printing success message.

options1: slightly update grammar

---

exercises/20_threads/threads2.rs
info.toml

Closes https://github.com/rust-lang/rustlings/issues/287

threads2: simplify the exercise

---

README.md

v1 wasn't updated for about 5 years.
@shadows-withal Awaiting your approval to remove the reference.

Remove the reference to v1

---

.github/workflows/rust.yml

ci: add `clippy` job to `rust.yml` workflow

---

exercises/23_conversions/from_into.rs

Noticed a small typo (missing a period at the end of the sentence) so I added it!

chore(from_into): Add missing period in docs

---

exercises/18_iterators/iterators4.rs

Since this is not about conversion, prefer the option that doesn't require one.

Unify fn signature in iterators4 exercise and solution

---

solutions/quizzes/quiz2.rs

The iterator solution uses a for loop in its body, to the dismay of functional programmers.. 🫠
We could use the repeat method in this situation!

Update iterator solution in quiz2.rs

---

rustlings-macros/info.toml

Fixed grammatical error, subject/verb agreement at line 124-125.

grammatical error in info.toml

---

exercises/03_if/if2.rs
solutions/03_if/if2.rs

Some people would get stuck on this exercise, trying to understand the meaning behind foo, fuzz, baz etc. Making the theme of the code make a little more sense to humans should hopefully prevent people from getting confused by abstract and non-sensical tests.

Make if2 less confusing

---

solutions/13_error_handling/errors6.rs

Discussed in https://github.com/rust-lang/rustlings/issues/2157
Let me know if you think this should be reworded or something else should be added.
Thanks!

errors6: Add alternative solution using From trait

---

exercises/13_error_handling/errors5.rs

Minor typo correction in exercise instructions

Fix typo - errors5.rs

---

rustlings-macros/info.toml

Fix typo in traits hint
