rust-lang/rustlings

- move_semantics/move_semantics1.rs
When I compile the unedited example in the playground, I get the
error on line 10, not line 8. That's the case for stable, beta,
and nightly. I'm a rust newbie, so for all I know the error is
supposed to be on line 8, but isn't due to some bug. I'm just
correcting the hint to match what I'm seeing.
Thank you for this project! I'm having fun and learning.
> Fix typo in hint for move_semantics1.rs.

- strings/strings2.rs
The hint in the `strings2` exercise was referencing a variable binding from a previous commit.
> Update hint to reflect new variable binding name

- move_semantics/move_semantics1.rs
- move_semantics/move_semantics2.rs
The referred to errors are actually in lines 11 and 10 resp.
Off topic: Great intro to Rust!
> Fixed two typos in hinttext

- error_handling/errors2.rs
- error_handling/errorsn.rs
- primitive_types/primitive_types3.rs
- primitive_types/primitive_types4.rs
- primitive_types/primitive_types5.rs
- primitive_types/primitive_types6.rs
- standard_library_types/iterator3.rs
- threads/threads1.rs
There is a bunch of book references in the hints within exercises that lead to the outdated version of the book (pages have a message "There is a new edition of the book and this is an old link." and require a bunch of digging to find the appropriate section of the book). This change updated the outdated links with the relevant ones, where possible. In one instance (primitive_types3.rs) the content is no longer available in the book, so I provided a direct hint on how to initialize an array of a specified size with values.
> update old book references to the second edition of the book

- src/main.rs
This might have issues on windows (I feel like colors in terminals always do), so it might be worthwhile to test this specifically on windows before any major use.
> Propagate colored output from rustc

- README.md
- exercises/error_handling/README.md
- exercises/functions/REAMDE.md
- exercises/if/REAMDE.md
- exercises/macros/README.md
- exercises/modules/README.md
- exercises/move_semantics/README.md
- exercises/standard_library_types/README.md
- exercises/tests/README.md
- exercises/threads/README.md
Sub READMEs contain the relevant resources from the main
README of the web version. All second edition Rust Book links
were updated to the 2018 edition.
Fixed to typos in main README.md.
> Created sub READMEs for CLI only version

- README.md
- Be more explicit re terminal commands
- Copy over "Need help?" section
- General wording
> Continued work on new readme

- src/main.rs
Currently watch mode only watches for `DebouncedEvent::Chmod` and `DebouncedEvent::Write`. There are some edge cases where these events wont be called even when a file is modified.
For example, if the user is using vim with swap files enabled, it seems like only a `Remove` and then `Create` event is called for the rust file. Usually this is okay because there will also be a swp file being modified, but if the user has their swap files placed in a different directory, `rustlings watch` does not work.
This fixes the issue by also listening for the `Create` event, and only triggering for .rs files (so swp file changes are ignored).
I'm guessing that this may be related to #111, as I ran into the same issue and started looking into why watch wasn't working.
> Watch for file creation events in watch mode

- src/main.rs
- src/verify.rs
When in `watch` mode, it's a pain to have to wait for all previous exercises to compile before the one you just saved compiles...so now it skips compiling any files up and to the one most recently saved.
> Start verification at most recently modified file

- src/main.rs
Before, rustlings would panic if it wasn't in the right directory. It
took me a minute to figure out why, and this wasn't my first intro to
Rust. It would probably help new users if they saw a helpful message
instead of a stack trace.
> Be nicer when rustlings isn't run from the right directory.

- install.sh
This addresses issue #128.
I would have liked to write some tests for the vercomp function I
introduce, but there doesn't seem to be any CI setup yet?
> Verify that rust version is recent enough to install rustlings.

- install.sh
1b3469f236bc6979c27f6e1a04e4138a88e55de3 has fixed the tests themselves, but now the original error shows itself.
> Fix order of true/false in tests for executables

- src/main.rs
@hades32 @guttume could you test whether this works on windows by checking out the branch locally and running `cargo run watch`?
> fix watch command path execution

- .travis.yml
- src/run.rs
- src/util.rs
- src/verify.rs
First public pull request 😬
There's an intermittent integration test failure when you use multiple test threads (at least for me on a mac). I narrowed it down to two tests each spawning a process using `Command` which then try to compile the same file at the same time. If the timing doesn't work out, they both try to compile, and then one process runs `clean` before the other can run the executable - causing a panic.
You can prevent it from happening by running with a single thread (`cargo test -- --test-threads=1`), because the `Command` blocks. That's not a particularly good solution though because it's not something you can configure in `Cargo.toml`.
I considered making the affected tests just run serially, but it occurred to me that this could also happen if someone accidentally runs …
> Fix intermittent test failure caused by race condition

- exercises/move_semantics/move_semantics4.rs
- exercises/test2.rs
Hi !
I played a bit with rustlings, and I felt that some exercises were incorrect because they passed the tests without me needing to edit the files!
This gave me the feeling that the exercise was skiped! Especially when I use `rustlings watch`, it is easy to miss an exercise because the compilation error that is displayed is the one of the next exercise ...
It is easy to identify "broken" exercises with:
```bash
% find exercises -name "*.rs" | xargs -n 1 rustlings run
...
✅ Successfully ran exercises/move_semantics/move_semantics4.rs
✅ Successfully tested exercises/test2.rs
```
My suggestion is to make sure that these files trigger a compilation error by adding a simple syntax error (e.g. with `???` in the code that must change) so that our Rustacean can then play with it!
> Add errors to exercises that compile without user changes

- exercises/error_handling/errors1.rs
Add Result type signature as it is difficult for new comers to understand Generics and Error all at once.
At first, I tried `Result<String, Error>` and got this.
```bash
error[E0412]: cannot find type `Error` in this scope
--> exercises/error_handling/errors1.rs:9:62
|
9 | pub fn generate_nametag_text(name: String) -> Result<String, Error> {
|                                                              ^^^^^ not found in this scope
help: possible candidates are found in other modules, you can import them into scope
|
1 | use std::error::Error;
|
1 | use std::fmt::Error;
|
1 | use std::io::Error;
|
```
In the book, it talks about `std::io::Error` with `Result` which is a bit confusing. See https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html
It took me a long time to …
> Update errors1.rs - Add Result type signature as it is difficult for new comers to understand Generics and Error all at once.

- tests/fixture/failure/testNotPassed.rs
- tests/integration_tests.rs
A previous version didn't run tests inside exercises. This pull request introduces one more test to cover such situation
> Add not passing integration test

- exercises/structs/README.md
- exercises/structs/structs1.rs
- info.toml
Thanks for rustlings! Here's a small contribution in return.
> Adds a simple exercise for structures

- exercises/standard_library_types/README.md
- exercises/threads/README.md
The links had the 2018 book in them and they were outdated.
> fixed outdated links

- exercises/threads/threads1.rs
> Fix link to Arc<T> in the book

- default_out.txt
- src/main.rs
- Make the default rustlings executable text consistent with the README and install script by adding `--force`.
- Remove a missed highlighting character from Issue #133.
> chore: Minor text updates

- install.sh
fixes #147 
I did some quick testing with the `-x` check:
```sh
if [ -x "$(notrustlings)" ]
then
echo "notrustlings does not exist"
else
echo "notrustlings appears to exist!"
notrustlings
fi
```
which produced:
```
./test.sh: line 12: notrustlings: command not found
notrustlings appears to exist!
./test.sh: line 17: notrustlings: command not found
```
(consistent with comments in issue)
Using `if ! [ -x "$(command -v <command>)" ]` appears to be the standard way to perform this type of check.
> fix(installation): Fix rustlings installation check

- exercises/structs/structs1.rs
PR https://github.com/rust-lang/rustlings/pull/163 accidentally introduced an error using some versions of the Rust compiler where the compiler would (rightly!) complain about an irrefutable let pattern. I have no idea why this did not occur in all versions of the compiler, but here is a way around it.
> Fixes the irrefutable let pattern warning in `structs1.rs`

- exercises/functions/functions5.rs
- exercises/if/if1.rs
- exercises/modules/modules2.rs
- exercises/move_semantics/move_semantics1.rs
- exercises/move_semantics/move_semantics2.rs
- exercises/move_semantics/move_semantics3.rs
- exercises/move_semantics/move_semantics4.rs
- exercises/primitive_types/primitive_types6.rs
- exercises/standard_library_types/arc1.rs
- exercises/standard_library_types/iterators3.rs
- exercises/test3.rs
I noticed some formatting that isn't consistent with the `rustfmt` style and tried my best to run it on the files in the exercises directory (which does fail for files that can't compile!), which just caught some minor whitespace things here and there.
Note: also can't just apply `rustfmt` blindly because of the blank lines that lead to the hint comments
> chore: Clean up some formatting in exercises

- exercises/error_handling/errorsn.rs
- exercises/functions/README.md
- exercises/if/README.md
- exercises/macros/README.md
- exercises/modules/README.md
- exercises/move_semantics/README.md
- exercises/primitive_types/primitive_types5.rs
- exercises/primitive_types/primitive_types6.rs
- exercises/strings/README.md
- exercises/tests/README.md
- exercises/threads/threads1.rs
- exercises/variables/README.md
While I was fixing these, I figured maybe it's good to just use a consistent URL for book links: https://doc.rust-lang.org/book/
Is there a plan for what to do with this old 1.4.0 example that doesn't exist in the current version of the book? Perhaps at least include a disclaimer when recommending that folks check it out?
https://github.com/rust-lang/rustlings/blob/34e31232dfddde284a341c9609b33cd27d9d5724/exercises/threads/README.md#L1
> chore: Fix a couple broken book links

- exercises/test1.rs
addressing a minor function naming convention, see: [RFC #430](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html)
closes #180
> fix(test1): renamed function name to snake case

- exercises/standard_library_types/iterators2.rs
- info.toml
Hi there!
I really enjoyed doing the rustlings exercises so I thought that I would try to add an exercise!
This one just covers a couple of basic iterator operations. Getting people used to the `map` and `collect` functions.
However, it does feel kinda similar to the next exercise. So I may also revisit some of the tests in iterators3 if we think that is necessary.
> feat(iterators2): adds iterators2 exercise including config

- src/main.rs
Prevent a panic if the file triggering the watch event is gone.
> Fix(watch): Check if changed exercise file exists before calling verify.

- exercises/test1.rs
`Expected` should come before `actual`, other wise it leads to confusing compiler messages, e.g.
```
note: expected type `()`
found type `{integer}`
```
There may be other tests that need updating, but this is as far as I am through the Rustlings course right now :)
> fix(test1): Swap assertion parameter order

- exercises/error_handling/option1.rs
- info.toml
Fixes the bug referenced in #160, but does not address the larger feature work referenced by the issue.
> fix(option1): Add test for prematurely passing exercise

- README.md
I'm pretty new to Rust. I tried installing rustlings for the first time and got this error:
```
$> cargo install --force --path .
error: `/Users/ajax/projects/rust/rustlings` is not a crate root; specify a crate to install from crates.io, or use --path or --git to specify an alternate source
Caused by:
failed to parse manifest at `/Users/ajax/projects/rust/rustlings/Cargo.toml`
Caused by:
editions are unstable
Caused by:
feature `edition` is required
this Cargo does not support nightly features, but if you
switch to nightly channel you can add
`cargo-features = ["edition"]` to enable this feature
```
I'm not sure if the answer was to run `rustup update` but I noticed that I was running Rust 1.29.0, so updated to 1.36.0 and got it working. If there's a way to specify a minimum required …
> Suggest rustup update in readme

- exercises/primitive_types/README.md
- exercises/primitive_types/primitive_types4.rs
- info.toml
I noticed this issue and it seems like a similar one was raised/fixed in #160 this way. This is my first contribution to this repo (or any Rust project) so let me know if I messed up or need to fix anything!
---
This commit converts primitive_types4 to a test and asserts that the
slice given is equal to the expected slice.
The intent of the primitive_types4 exercise appears to be to ensure the
user understands inclusive and exclusive bounds as well as slice syntax.
`rustlings` commands using `compile` do not verify that a specific
println is reached and, in the case of `watch` and `verify` (but not
`run`), they do not output the `println`s at all.
This fix is semantically similar to #198. It does not take a stance on
the correct way to handle this for all exercises; see #127. There are …
> fix(primitive_types4): Fail on a slice covering the wrong area

- install.ps1
Adds a powershell install script for windows users that are at least
running powershell 5. It is almost a direct port of install.sh.
This would be used to automatically download the script much like
curl | bash, but with:
`Invoke-WebRequest https://urltoscript.com | Select-Object
-ExpandProperty Content | Out-File $env:TMP/install_rustlings.ps1;
Unblock-File $env:TMP/install_rustlings.ps1; Invoke-Expression
$env:TMP/install_rustlings.ps1`
> Add windows install script

- Cargo.lock
I think this may have been intended for inclusion in 4f0c5a8d49a9164f4174d82d86b0bbba40badc4e. The rls in VS Code is being pretty adamant about updating it, so I thought I'd PR the change :)
> chore: Bump version in Cargo.lock

- exercises/error_handling/option1.rs
@Zazcallabah pointed out that the second argument passed to `assert!` didn't make much sense in this context. This PR removes that second argument to clarify what is being asserted / tested in this exercise.
> fix(option1): Fix arguments passed to assert! macro

- src/main.rs
Fixes #146 
If someone is sliding in and out of "watch" mode, it can make it hard
to tell which error messages are still relevant. This patch resolves
that by clearing the terminal entirely before entering watch's loop.
Note that the escape character is chosen for compatibility reasons, because different shells/terminals can change which commands they accept or have installed, betting on what other commands are in use to collect data seems risky, and just expecting them to implement ANSI escape code sequences is more reliable. This seems especially true since Windows is seeking more UNIX compatibility in its terminals going forward, even though it doesn't implement the POSIX standard per se.
> watch: clears terminal before entering loop

- exercises/enums/README.md
- exercises/enums/enums1.rs
- exercises/enums/enums2.rs
- exercises/enums/enums3.rs
- info.toml
Creates an exhaustive list of enum exercises. This goes through the basics of different ways to derive enums with mixed data type variants, as well as the use of the all important `match` operator.
> feat: Add enums exercises

- src/main.rs
Addresses #190. From the backtraces shown there, it seems like we're not able to launch `rustc` (which is odd, given that they probably compiled and installed `rustlings` :woman_shrugging:)
> feat(cli): check for rustc before doing anything

- Cargo.lock
- Cargo.toml
- src/run.rs
- src/verify.rs
- tests/fixture/state/finished_exercise.rs
- tests/fixture/state/info.toml
- tests/fixture/state/pending_test_exercise.rs
- tests/integration_tests.rs
`watch` and `verify` do prompt the user to actively move to the
next exercise. This change fixes `run` to never prompt. Previously
it was inconsistent between "test" and "compile" exercises.
BREAKING CHANGE: we again change the behavior of the `run` command
> fix(run): makes `run` never prompt

- info.toml
In functions4, the missing code is in line 14 in the latest version:
```rust
error: expected type, found `{`
--> exercises/functions/functions4.rs:14:30
|
14 | fn sale_price(price: i32) -> {
|                              ^ expected type
error: aborting due to previous error
```
but the hint points to line 12. This is due to a recent change in 2cdd61294f0d9a53775ee24ad76435bec8a21e60.
Also includes similar updates for strings2 and primitive_types4.
> Update line numbers in hints and outdated comment

- exercises/move_semantics/move_semantics2.rs
- exercises/threads/threads1.rs
- info.toml
The introduction of `I AM NOT DONE` shifted the lines of all exercises, which now need adjustment.
> fix: line numbers in several exercises and hints

- src/main.rs
- src/verify.rs
`rustlings hint ...` command is not convenient when doing exercises with `rustlings watch`.  
This PR makes it possible for user to type `hint` while running `watch`  and get hint text for exercise which is currently failing.
e.g.
```rust
...
--> exercises/variables/variables1.rs:13:36
|
13 |     println!("x has the value {}", x);
|                                    ^ not found in this scope
error: aborting due to 2 previous errors
For more information about this error, try `rustc --explain E0425`.
type 'hint' to get help:
hint
Hint: The declaration on line 12 is missing a keyword that is needed in Rust
to create a new variable binding.
```
> feat(watch): show hint while watching

- exercises/enums/README.md
After being stuck on exercise enums3.rs for about an hour or two, having read the entire chapter on enums 2-3 times, and still being unable to complete the exercise, i started broadening my reading. I finally found the answer in the rust docs via google.
> fix(enums): Add link to chapter on pattern syntax

- exercises/conversions/README.md
- exercises/conversions/as_ref_mut.rs
- exercises/conversions/from_into.rs
- exercises/conversions/from_str.rs
- exercises/conversions/try_from_into.rs
- exercises/conversions/using_as.rs
- info.toml
This pull request adds exercises for converting values into specific types. The exercises uses string to struct type conversions, but most of the traits in the exercises can handle more than just string parsing and conversions.
The following traits are covered:
1. `From` and `Into`
2. `TryFrom` and `TryInto`
3. `AsRef`
4. `FromStr`
The `as` operator is also covered.
> feat: Add type conversion and parsing exercises

- README.md
Added an essential step to Windows installation process (Setting ExecutionPolicy to RemoteSigned because it wouldn't install otherwise).
> fix(docs): Added a necessary step to Windows installation process

- src/main.rs
The completion message is shown only once all exercises succeed and are
not annotated with "I AM NOT DONE." The watch command will also exit
closes #251
Let me know if there are any tests I could add or if the completion message should be tweaked!
> feat: Show a completion message when watching

- Cargo.toml
Some of the versions of dependencies pulled in the older winapi / kernel32 libraries. Kernel32 is no longer needed as it's all in the new version of winapi. This did not work on windows aarch64 and thus prevent rustlings from working natively on devices like the Surface Pro X.
> fix: Update deps to version compatable with aarch64-pc-windows

- install.sh
I initially ran the installation script without rust installed. The fact that the error message was labeled with WARNING made me unsure whether installation was successful or I needed to re-run after installing rust. There's an error code returned on fatal errors, but this change will make things clearer.
> fix(installation): make fatal errors more obvious

- exercises/test4.rs
- info.toml
Enable test mode for exercise test4.rs, and add a new test case. This exercise was easy to "pass" by e.g. writing a macro which returned a constant string literal, unless you ran `main` and looked at the output.
> Enable test for exercise test4

- src/exercise.rs
- src/main.rs
- src/run.rs
- src/ui.rs
- src/verify.rs
After working a bit on #270, I realized that it'd be useful to first perform a minor refactor of exercise evaluation.
* Now we have standard methods to compile + execute that return `Result`s.
* Success/failure messages are standardized.
> refactor: exercise evaluation

- .gitignore
- exercises/clippy/README.md
- exercises/clippy/clippy1.rs
- exercises/clippy/clippy2.rs
- info.toml
- install.ps1
- install.sh
- src/exercise.rs
- src/run.rs
- src/verify.rs
This is a feature PR which adds the possiblity to create clippy exercises.
Clippy has many awesome linting rules, which can give a deeper understanding about the Rust programming language, therefor I made this PR.
> feat: Add clippy lints

- exercises/conversions/from_into.rs
This PR adds an additional test to meet this exercise [rule](https://github.com/rust-lang/rustlings/blob/master/exercises/conversions/from_into.rs#L33).
> Adds additional test to meet exercise rules

- Cargo.lock
- exercises/option/README.md
- exercises/option/option1.rs
- info.toml
I have added a basic Option exercise. I plan to add more exercises if this gets accepted. Let me know what to fix / change. I copied some formatting stuff from other exercises.
> feat: added option exercise

- exercises/primitive_types/primitive_types4.rs
- src/verify.rs
- tests/integration_tests.rs
* New: `mode = "output`.
* If `output = "foobar"` is specified for an `"output"` exercise, it runs a "test" against the expected output.
* An `"output"` exercise prints its output in the `🎉 Move on when you're ready` screen. 
<details>
<summary> Screenshots </summary>
</details>
After playing a while with this, I'm not entirely sold on the idea :sweat_smile: I think having expected output _could_ be useful in a very exploratory exercise like "Get `main` to print `Hello world!` to the screen". But, in general, I feel like `"test"` exercises guide you better toward the answer. Take `structs1.rs` for instance and its hypothetical alternative:
<details>
<summary> <code>structs1.rs</code> </summary>
```rust
struct ColorClassicStruct {
// TODO: Something goes here
}
struct ColorTupleStruct(/* …
```
> feature: adds "output" mode, resolves #270

- exercises/option/option2.rs
- info.toml
I added another exercise for Option<T>, as promised.
Let me know if there are any problems with this.
This one is specifically about if let / while let
> feat: Add Option2 exercise

- exercises/conversions/as_ref_mut.rs
As indicated in #259 , I found it confusing to have 2 comments as the code wouldn't compile unless I solved both issues (I used the script from #281 to remove a comment and use `:wn` to go to next exercise, hence this tripped me).
> Remove duplicate not done comment

- src/exercise.rs
Additionally to running clippy, also compile the exercise file so that
`rustling run clippy1` works after a successful completion of the
exercise.
> fix(run) Compile clippy exercise files 

- Cargo.lock
- info.toml
chore: update variables5.rs book link
> chore: update variables5.rs book link

- exercises/variables/variables6.rs
- info.toml
The 'Variables and Mutability' section of [The Book](https://doc.rust-lang.org/stable/book/ch03-01-variables-and-mutability.html) introduces the _const_ keyword. However, that seemed to not be covered by the variables exercises.
> feat: Add exercise variables6 covering const

- exercises/conversions/try_from_into.rs
There is a confusing comment in conversions/try_from_into.rs due to the copy/paste from from_into.rs task. Fixed it.
> fix confusing comment in conversions/try_from_into.rs

- exercises/clippy/clippy1.rs
I noticed while investigating [#300 ](https://github.com/rust-lang/rustlings/issues/300) that it's a little jarring when transitioning to the `Mode::Clippy` exercises, as it's not immediately clear that the code fails to compile due to clippy warnings.
I have added comments to clippy1 to clarify the compilation failures are from clippy.
> chore: add explanatory comment to clippy1

- info.toml
> Fix missing space in the hint for errorsn.rs

- install.sh
The `bash`installation script is edited to make sure that we're checking that there is an installation of `python` available on the machine.
We start by checking for `python3`, then falling back to `python`. If neither is available, we check one last time for `python2`. If none of these is successful, we exit the script with a return code of `1`.
closes #374
Thank you,
Abdou
> Check if python is available while checking for git, rustc and cargo

- exercises/macros/README.md
- exercises/standard_library_types/iterators2.rs
- exercises/standard_library_types/iterators4.rs
- info.toml
- /macros/README.md: Typo "modules" => "macros"
- iterators2.py: Reduce line length to <90-char width.
- iterators4.py: Update 'fun' => 'challenge' as per PR#177
- rustlings hint iterators4: improve clarity
> fix: update iterator and macro text for typos and clarity

- exercises/error_handling/errorsn.rs
When I was working on error_handling/errorsn.rs I notice that warning.
```
warning: use of deprecated item 'std::error::Error::description': use the Display impl or to_string()
--> exercises/error_handling/errorsn.rs:103:49
|
103 |         f.write_str((self as &dyn error::Error).description())
|                                                 ^^^^^^^^^^^
|
= note: `#[warn(deprecated)]` on by default
```
> chore: Remove deprecated description from error_handling/errorsn.rs

- exercises/if/if2.rs
- exercises/option/option1.rs
- info.toml
This PR implements two things: 
1. A new `if2` exercise that shows the type of compiler message you get if your conditional branches don't return the same type as well as the usage of `else if`
2. A small change to the option1 exercise that I think makes it very confusing (no problem dropping this one if there's disagreement here).
> if2 exercise and option1 fix

- info.toml
Array initialization / default variables is unrelated to Options and not overtly mentioned beforehand.  
As the question is about Options, it is easy for someone new to Rust to misunderstand and look elsewhere for a solution.
> fix(options1): Add hint about Array Initialization

- exercises/test2.rs
I know this is quite boring, but while we are putting backticks, it's good to be more accurate.
> fix(test2): name of type String and &str

- exercises/conversions/from_str.rs
- exercises/conversions/try_from_into.rs
- info.toml
English is not my native language, so I may have made some mistakes in the text. I would be grateful if someone could check it out.
closes #392
> feat: Rewrite try_from_into

- exercises/option/option2.rs
I think a simple add of "TODO" will make this exercise look more in line with the other exercises.
Other exercises included a "TODO" before when the programmer was expected to enter a solution.
> fix(option2): Add TODO to comments

- exercises/structs/structs2.rs
There was a hint added for struct2 by https://github.com/rust-lang/rustlings/pull/355, so this comment is misleading.
> remove struct2 hint comment

- README.md
Emphasizes that the Windows commands in the README only work in Powershell, not in cmd (in response to PR #373 ).
> chore: Add Powershell reminder (PR #373)

- exercises/generics/generics3.rs
Makes the line length consistent with the other exercises.
> chore: Limit generics3 lines to 90 chars

- exercises/option/option1.rs
If you decide to print the elements in `numbers`, it will display only zeros, which can be confusing.
This change makes the numbers a little bit bigger.
```
printing: 0
printing: 0
printing: 0
printing: 0
printing: 0
vs
printing: 0
printing: 19
printing: 38
printing: 57
printing: 77
```
> fix(option1): Don't add only zeros to the numbers array

- .gitignore
- exercises/standard_library_types/README.md
- exercises/standard_library_types/box1.rs
- info.toml
Having completed all of the existing exercises, I noticed there wasn't one with the `Box` type.
Although this exercise alone might not completely solve https://github.com/rust-lang/rustlings/issues/403, I think it's a start 🦀 .
> feat: Add box1.rs exercise

- info.toml
... rather than leaving them in the dark.  It doesn't matter how much I "Think carefully about what we need to do here." if I don't already understand, (and have memorised) ch10 of The Rust Book. Even if one understand the concept of generic types, expecting the student to determine the specific Rust grammar from first principles, might be considered to be asking a little too much.
> fix(generics2): Guide students to the answer

- README.md
To run `Invoke-WebRequest` you have to have the Internet Explorer Feature enabled, and you must have opened Internet Explorer at least once, which some people may not have (me for example).
If you don't you will receive an error and the install will fail. 
This also simplifies the download command (imo).
`Start-BitsTransfer` is a drop in replacement which doesn't need you to have internet explorer enabled.
_apologies if the commit naming is wrong, i wasn't sure what commit type this would fall under._
> docs: Update `Invoke-WebRequest` to `Start-BitsTransfer`

- info.toml
- install.sh
- src/exercise.rs
- src/main.rs
- src/run.rs
- src/verify.rs
- tests/fixture/success/testSuccess.rs
- tests/integration_tests.rs
This new feature can be accessed by invoking rustlings with `--nocapture`.
closes #262
**_MINOR CHANGES_**:
* Documentation added to source code under [`src`](https://github.com/rust-lang/rustlings/tree/master/src)
* Both unit and integration tests for `--nocapture` have been added.
**_BREAKING CHANGES_**:
The following function take a new boolean argument:
* `run`
* `verify`
* `test`
* `compile_and_test`
`compile_and_test` is the function that uses this new boolean argument to determine whether or not to display the output from the test harnesses.
Please feel free to reach out with any questions.
Thank you,
Abdou
> Show tests prints

- exercises/standard_library_types/arc1.rs
Ensure that std::sync::Arc is actually used, as this exercise can be compiled using things already learnt in previous exercises.
> fix(arc1): Passively introduce attributes

- exercises/structs/structs3.rs
rename confusing "from" and "to" to sender_country and recipient_country as suggested
> fix : Use of integer for prices, therefore also for weight

- info.toml
Fixes typo in hint. Makes more grammatical sense changing `then` to `than`.
Resolves #455.
> fix: Change then to than

- src/verify.rs
Suggestion from AbdouSeck https://github.com/rust-lang/rustlings/issues/424#issuecomment-639870331 for when the student's code has errors.
(Works for me, but I haven't done extensive testing to check how this could impact other exercises, so this should be reviewed by someone more competent than me, before merging.)
> feat: Remind the user of the hint option

- exercises/enums/enums3.rs
> fix(enums3): Update Message::ChangeColor to take a tuple.

- README.md
Resolves #459.
Encourages the reader in terms of what to do after completing Rustlings, and then provides clear uninstallation instructions, if they'd like to do so.
> docs: Add uninstall info to README.md

- exercises/conversions/try_from_into.rs
It seems to me like if we're already testing for an overly long slice, we might as well check for one that is too short as well.
> feat(try_from_into): Add insufficient length test

- src/main.rs
feat(cli): Added 'cls' command to 'watch' mode
> feat(cli): Added 'cls' command to 'watch' mode

- Cargo.lock
I've noticed this in my changed files while going through the exercises.
> fix: Update rustlings version in Cargo.lock

- exercises/macros/macros4.rs
Did you mean this? I'm new to rust and this test passed right away, so unsure what the intention was.
> Make macros4 not compile by default

- exercises/conversions/using_as.rs
- info.toml
It was pretty easy (at least for me), to get this to compile but return an incorrect value. I've added a test to ensure the proper type is used.
Using a `usize` cast:
Using `f64`:
Seems like the test is helpful to avoid that.
> fix(using_as): Add test so that proper type is returned.

- exercises/structs/structs3.rs
A small follow-up to PR #432, where the price of kg was changed to price per gram to avoid usage of floats. The variable identifier should therefore also be changed, because `cents_per_kg` would indicate 3/1000 and not 3.
> fix(structs3): Small adjustment of variable name

- exercises/conversions/from_into.rs
A typo in the fn test_bad_age() hint message had a point rather than comma
Prev:
// Test that "Mark.twenty"
Current:
// Test that "Mark,twenty"
>  chore: Change point to comma in from_into.rs

- src/exercise.rs
Looks like this was copied from the previous test without renaming. This test is currently failing `cargo test` and ticket https://github.com/rust-lang/rustlings/issues/542 has been raised.
> fixed test name

- exercises/tests/tests3.rs
The second test is meant to test passing an odd result, so let's make the name reflect that.
> fix(quiz3): Second test is for odd numbers, not even.

- exercises/primitive_types/primitive_types6.rs
To keep constancy with `primitive_types4.rs` I suggest to add a test in `primitive_types6.rs` this suggestion comes from my students because some students were just typing any numbers.
Also added a little indication in order to avoid passing solution with just typing the number. Also it's possible to type out `numbers.???` to avoid this possible unexpected outcome I got it in class this week.
If it's not an issue or if this not merge-able in this state I am open to discussion! :)
> feat(primitive_types6): Add a test

- info.toml
primitive_types6 exercise was changed to test yesterday, but info.toml file wasn't updated.
I think this change should fix it.
> chore: primitive_types6 mode changed to test

- exercises/collections/README.md
- exercises/collections/hashmap1.rs
- exercises/collections/hashmap2.rs
- exercises/collections/vec1.rs
- exercises/collections/vec2.rs
- info.toml
Since `Vec` and `HashMap` are two fundamental data structures that are used often in every programming languages, I added 4 new exercises for them.
- The "collections" exercises has been added after the "modules" and before the "macros" exercises.
- `vec1.rs` and `vec2.rs` for exercises related to `Vec`tors. First exercise focuses on declaration of vectors and second exercise focuses on iteration and mutability.
- `hashmap1.rs` and `hashmap2.rs` exercises for `HashMap`s. First exercise focuses on declaration and insertion. Second exercise focuses on `entry()` API.
Open to any improvements or suggestions!
> Add "collections" exercises

- install.ps1
- install.sh
closes (sort of?) #577
The addition of --show-output when exercises are run in test mode in #422 means that rustlings no longer works properly on rustc < 1.39.
> fix(installation): Update the MinRustVersion

- exercises/conversions/try_from_into.rs
Hello everyone :smile:. I was trying to resolve the `try_from_into` exercise and found out that I passed all the tests if I sum up for example all elements in array and test if it is <= 765 or >= 0. But if we sum up `(255 + 255 + (-1))` it gives us a good result but the third value is negative, so we should not pass it.
I added 3 tests for each type to prevent users pass this type of errors.
Example for array:
```rust
// Array implementation
impl TryFrom<[i16; 3]> for Color {
type Error = String;
fn try_from(arr: [i16; 3]) -> Result<Self, Self::Error> {
if arr[0] + arr[1] + arr[2] <= 765 && arr[0] + arr[1] + arr[2] >= 0 {
let c = [arr[0] as u8, arr[1] as u8, arr[2] as u8];
Ok(Color {
red: c[0],
green: c[1],
blue: c[2],
})
} else {
Err("NOP".to_string())
}
}
}
```
This code passes all the …
> feat(try_from_into): Add tests

- info.toml
The hint for structs1 improperly stated that there are 2 types of structs. Updated to clarify there are 3.
I changed the link to the page related to the exercise directly, though the one previous link is not necessarily wrong as it is one page before the link I prefer.
> fix(structs1): Adjust wording

- exercises/conversions/try_from_into.rs
> fix(try_from_into): Update description

- exercises/collections/vec1.rs
The previous test would stop comparing elements in array a and vec v upon reaching the last element of either. This resulted in the test passing even if v did not contain all the elements in a. This change to the test fixes that bug and should only pass if all the elements in a and v are present and equal.
> fix(vec1): Have test compare every element in a and v

- exercises/README.md
- info.toml
Exercises are not organized in order for ```rustlings watch``` and it was hard to follow the exercises because we always had to jump back and forth between chapters.
1. Updated exercise order to match that of book chapters
2. Added exercise to book chapter mapping table to exercise README.md
> feat: match exercise order to book chapters

- exercises/README.md
- info.toml
> fix: added missing exercises to info.toml

- exercises/functions/functions2.rs
Now trigger this error:
```
error: expected type, found `)`
--> exercises/functions/functions2.rs:10:16
|
10 | fn call_me(num:) {
|                ^ expected type
```
> fix #539: Change signature to trigger precise error message:

- info.toml
[`Option::flatten`](https://doc.rust-lang.org/std/option/enum.Option.html#method.flatten) is so useful, I thought I would mention it as an alternative to "stacking Options".
Thanks for considering this, I've been having fun with `rustlings` and hope to make more substantial contributions in the future. :smile:
> docs: mention flatten in the options2 hint

- src/exercise.rs
- src/main.rs
- tests/fixture/state/info.toml
- tests/integration_tests.rs
The PR is two-fold:
1. `rustlings list` should now display more than just the exercise names. Information such as file paths and exercises statuses should be displayed. The `--paths` option limits the displayed fields to only the path names; while the `--names` option limits the displayed fields to only exercise names. You can also control which exercises are displayed, by using the `--filter` option, or the `--solved` or `--unsolved` flags.
**Sample invocations**:
```sh
rustlings list --filter "trait,enum,struct"
rustlings list --unsolved
```
This portion should also close #281.
**Some shell utility use cases**:
- Fetching pending _exercise file paths_ with the keyword "conversion" to pass to my editor:
```sh
vim $(rustlings list --filter "conversion" --paths --unsolved)
```
- Fetching …
> feat(cli): Improve the list command with options, and then some

- exercises/conversions/from_str.rs
The steps currently tell the user to return an error but the tests check for panic.
This updates the instructions to make it clearer that if the extraction/parsing fails, a panic should be raised
> Fix instructions(steps) for conversions/from_str exercice

- exercises/structs/structs3.rs
Current version of structs3 exercise allows naive implementation of `is_international`. Tests pass if we merely return `true`. I added a test that creates a domestic package (i.e. sender and receiver country are the same)
More importantly, as someone new to Rust I wasn't sure if Strings get compared "by reference" or "by value", so I wondered if 
```Rust
fn is_international(&self) -> bool {
self.sender_country != self.recipient_country
}
```
would just _always_ return `true` (because they're objects on two different parts of the heap). Adding my test for a local package means my above implementation would be wrong if Strings weren't compared by value.
> fix(structs3): Add check to prevent naive implementation of is_international

- info.toml
The mode for `errors3` is set as `test` but the file does not contain any tests.
The generated output is hidden because it is in test mode. This obfuscates a successful result, impeding understanding.
An unrelated auto-formatting change removes trailing whitespace further down in the file.
> Changed errors3 mode from test to compile.

- exercises/collections/README.md
C++ `map` is more like BTreeMap in Rust.
`unordered_map` in C++(11) is the equivalent of `HashMap` in Rust.
(+ additional like for references).
> Fix Rust's HashMap equivalent in C++

- exercises/quiz3.rs
Adds by the way an example of unimplemented!() macro.
> Force an answer to Q2 of quiz3

- exercises/structs/README.md
By capitalizing the `c` letter it makes clear that we're talking about the C programming language.
> capitalize `c` letter

- README.md
The old ones pointed to `master` (I found this via #673), and because git.io has immutable links, we need a new one.
> chore: Update install URLs

- src/exercise.rs
- src/ui.rs
- src/verify.rs
When the `NO_EMOJI` environment variable is set, replace/eliminate emojis in output.
For instance, without `NO_EMOJI` set (normal behaviour):
With `NO_EMOJI` set:
Addresses #364.
> Replace emojis when NO_EMOJI env variable present

- exercises/functions/functions3.rs
Hi!
Going through the exercise functions3.rs, it feels like using u32 instead of i32  could be an improvement. Even though passing a negative number won't make the compiler complaint and the loop will exit immediately, it feels that it lacks of intention (to the eyes of someone who's learning like me). I hope this small change makes sense.
> fix: improve function argument type in functions3.rs

- exercises/conversions/from_str.rs
- exercises/conversions/try_from_into.rs
- info.toml
Use `Box<dyn error::Error>` to allow solutions to use `?` to propagate
errors.  In the tests, explicitly check `is_ok()` instead of trying to
force the error type to `String` (or other `PartialEq` type) using
`assert_eq!()`.
> fix: use trait objects for try_from_into

- exercises/collections/hashmap2.rs
Since the other fruits appear to use (American) English, I'm updating Lychee to do the same. The alternative to this would be to use the other name, which is "Litchi". 
chore: Rename 'Lichi' to 'Lychee'
> Rename 'Lichi' to 'Lychee' in the fruit example

- src/exercise.rs
- src/main.rs
- src/ui.rs
- src/verify.rs
Added a progress info at the bottom of the list for command: `rustlings list`
closes #705
> feat(list): added progress info

- README.md
Added hint for `rustlings list` to the "Doing exercises" section.
> docs: added hint for rustlings list command

- exercises/collections/hashmap2.rs
The test `at_least_five_types_of_fruits` implies that there should be `at least` five types of fruit in the basket, but the test is actually checking for `exactly` five types of fruit, which was a bit misleading for newcomers like me :) 
A simple change from `==` to `>=` should do the trick and properly check for the `at least 5` condition.
> Fix incorrect hashmap2 test

- exercises/option/option2.rs
Renaming uninformative names like `optional_value`, `value`, `optional_values_vec` and `value` helps users distinguish between the two parts of the task.
> Updated option2.rs

- exercises/structs/README.md
I was unable to do structs3 exercise until I read chapter 5.3 of the book. Hence, 5.3 should be in the structs README :)
> fix: Add 5.3 to structs/README

- exercises/standard_library_types/iterators3.rs
- info.toml
Adapted all but one compiler error into logic errors. The exercise can be tested after completing step one, without the need for the tests to be commented out.
The assertions against debug output are kept to allow the code to compile before `result_with_list` and `list_of_results` are completed. They also prevent the compiler from revealing the answer too eagerly.
﻿
> Enabled iterators3.rs to run without commented out tests.

- exercises/standard_library_types/iterators2.rs
- info.toml
Moved all errors out of tests and into the base module.
The exercise compiles after step 1 allowing the user to test `capitalize_first`. The remaining steps fix the other two failing tests.
The exercise still showcases the power of `collect` without requiring the user to complete the entire exercise before checking their work.
The hint to solve the `capitalize_first` function was moved to the hint in `info.toml`.
Closes #359
> Moved iterators2.rs errors out of tests.

- exercises/standard_library_types/iterators5.rs
- info.toml
Added an iterator exercise that counts values in a hash map that equal a given value.
Incorporates more iterator methods into the exercises. Provides a use case for the `fold` method.
> Added iterators5.rs exercise.

- Cargo.lock
- Cargo.toml
- src/exercise.rs
- src/main.rs
- tests/integration_tests.rs
I’ve been wanting to do this for a while, but always procrastinated on it. We’ve been using Clap since the 2.0 rewrite, but Clap is known to be a fairly heavy library. Since Rustlings is usually peoples’ first contact with a Rust compilation, I think it’s in our best interests that this complation is as fast as possible. In effect, replacing Clap with the smaller, structopt-style `argh` reduces the amount of crates needing to be compiled from 82 to 60.
I also think this makes the code way easier to read, we don’t need to use Clap’s methods anymore, but can switch over to using pure Rust methods, e.g., switches are booleans, options are Option<String>s or the like, and subcommands are just structs.
I'll leave this up for a couple of days for people to review and test, and this'll also be …
> feat: Replace clap with argh

- exercises/error_handling/README.md
add additional help information provided by the rust by example book, since the previous help pages didn't cover the whole section, especially error_handling/errorsn.rs was a bit difficult for me.
Those 2 added help pages will explain Result and Boxing errors very easily without much text to read.
> docs(errors): add additional help for Result/Boxing

- exercises/generics/README.md
add help for bounds provided by the rust by example book since the previous help doesn't explain bounds / generic constraints which is needed to solve *generics3.rs*.
> docs(generics): add bounds help

- exercises/clippy/README.md
- exercises/collections/README.md
- exercises/conversions/README.md
- exercises/enums/README.md
- exercises/error_handling/README.md
- exercises/functions/README.md
- exercises/generics/README.md
- exercises/if/README.md
- exercises/macros/README.md
- exercises/modules/README.md
- exercises/move_semantics/README.md
- exercises/option/README.md
- exercises/primitive_types/README.md
- exercises/standard_library_types/README.md
- exercises/strings/README.md
- exercises/structs/README.md
- exercises/tests/README.md
- exercises/threads/README.md
- exercises/traits/README.md
- exercises/variables/README.md
all exercises readme files now have a consistent structure and a (meaningful) description. For those without a description I picked some lines from The Book or Rust by Example.
All README.md files start with a heading 1 which includes the name of the exercises section, followed by some description and / or direct help and ends with a heading 2 further information which often points to The Book or Rust by Example.
Rendered examples:
- [Clippy](https://github.com/Zerotask/rustlings/blob/update-exercises-readme/exercises/clippy/README.md)
- [Generics](https://github.com/Zerotask/rustlings/blob/update-exercises-readme/exercises/generics/README.md)
- [Threads](https://github.com/Zerotask/rustlings/tree/update-exercises-readme/exercises/threads/README.md)
- …
> docs(exercises): consistent excersises README.md files

- src/main.rs
`rustlings watch` will now show an additional hint for the corresponding README.me
This will make it easier for learners to find the corresponding README.md file if they are stuck.
> chore(watch): add hint for the exercises README.md

- README.md
Running the command in `PowerShell` will fail if it's not opened with admin rights, I thought specifying this would make things more clear and save time
> updated README.md; specify need for admin rights

- info.toml
Add hints about how to return the correct type for functions that
return `Result<_, Box<dyn Error>`. Some feedback from Discord suggests
that people run into trouble with that.
> fix(try_from_into, from_str): hints for dyn Error

- exercises/move_semantics/move_semantics5.rs
- exercises/option/option3.rs
- info.toml
- Added an exercise for `move_semantics` which helps in improving the understanding of mutable references.
- Added an exercise for `option` which helps in understanding of usage of keyword _ref_
> feat: Add move_semantics5 exercise.

- exercises/move_semantics/move_semantics5.rs
- info.toml
Improve hints and comments for move_semantics5 based on repeated instances of people expressing confusion about this exercise on Discord.
>  fix: move_semantics5 hints

- exercises/standard_library_types/iterators5.rs
- info.toml
To allow more flexibility in solutions, derive `Clone` and `Copy`
for `Progress`.
Fixes #763.
Also add a hint about conciseness by using some method other than `fold`.
> fix(iterators5): derive Clone, Copy

- info.toml
`collect()` needs some hint for standard_library_types/iterators3 exercise with doc link for understanding different return types via `FromIterator`.
> chore: Update hint of iterators3

- README.md
- src/main.rs
Based on #783 
This PR should allow users to use the following command to run the next unsolved exercise in the `exercises` vector.
```bash
rustlings run next
```
When there are no more unsolved exercises, it will print the following messages and `exit` with `1`.
```
🎉 Congratulations! You have done all the exercises!
🔚 There are no more exercises to do next!
```
> [CLI] Feature: Add "next" to run the next unsolved exercise.

- README.md
ExecutionPolicy to RemoteSigned command must be fixed because the old command was getting denied access to change the Execution Policy property
> fix(installation): first PowerShell command

- exercises/quiz1.rs
The original text `order amount` appears to be confusing as it seems to imply that the function accepts an amount/price. However, the function is instead returning a price while the argument accepted into the function is the quantity of apples bought.
> chore: Updated quiz1.rs question description

- exercises/quiz1.rs
The second test expects the function to return 80 when there is an order of 40 apples, but the current wording implies returning 40 will pass as well
> Fix inconsistent wording

- exercises/README.md
- exercises/modules/README.md
- exercises/modules/modules1.rs
- exercises/modules/modules2.rs
- exercises/modules/modules3.rs
- info.toml
I updated the module exercises a little bit and changed the book dependency to be all chapter 7 and not only 7.2.
I'm new to rust and I'm learning by reading the book and exercise with rustlings. Yesterday I reached the modules exercise and it was very shallow compared to what they show in the book and 7.2 just isn't enough to answer the exercise (and chapter 7 of the book is very good by the way). Improving the module exercise could be very nice to future learners because it's important part of rust.
> Update modules exercise

- src/exercise.rs
Hi, I found and fixed typos in `src/exercise.rs`. btw, thanks for the great job rustlings have done.
> fix(exercise): typo

- src/main.rs
Includes:
- quit, to quit the shell instead of having to press Cmd/Ctrl-C or Cmd/Ctrl-D
- help, to display an overview of all the commands available in watch mode.
Closes #842.
> feat: add more watch commands

- exercises/move_semantics/move_semantics5.rs
Instead of having to explain why 
```rs
let mut x = 100; 
let y = &mut x;
let mut z_owned = *y;
let z = &mut z_owned;
*y += 100;
*z += 1000;
```
and 
```rs
let mut x = 100; 
let y = &mut x;
let z = &mut *y;
*y += 100;
*z += 1000;
```
are different, you still get the point across about having only one mutable reference.
As it stands, this exercise does too much (dereferencing and having only one mutable reference), and by doing so confuses people.
Example of someone being confused by this:
<https://discord.com/channels/273534239310479360/273541522815713281/872689531428692040>
(this is in the rust community discord <https://discord.com/invite/rust-lang-community>)
> Change &mut *y to &mut x

- exercises/advanced_errors/advanced_errs1.rs
- exercises/advanced_errors/advanced_errs2.rs
- exercises/conversions/from_str.rs
- exercises/conversions/try_from_into.rs
- info.toml
Based on #780.
Add new exercises to demonstrate traits that are useful to help other code consume our custom error types.
For `advanced_errs2`, I'm somewhat concerned that the `source` method usage in the ignored test might be lead to confusing error messages about that method, so I'm OK with taking out that test (and the related challenge), possibly deferring it to another exercise.
> feature: advanced errors

- exercises/conversions/from_str.rs
- exercises/conversions/try_from_into.rs
- info.toml
Remove the use of trait objects as errors from `from_str` and
`try_from_into`; they seem to have caused a lot of confusion in
practice. (Also, it's considered best practice to use custom error
types instead of boxed errors in library code.) Instead, use custom
error enums, and update hints accordingly. Hints also provide
some guidance about converting errors, which could be covered
more completely in a future advanced errors section.
Also move from_str to directly after the similar exercise `from_into`,
for the sake of familiarity when solving.
> fix(from_str, try_from_into): custom error types

- exercises/structs/structs3.rs
Intended to simplify the lesson by removing the need to figure out what the value is meant to be based on the test.
Previous commits (https://github.com/rust-lang/rustlings/commit/9ca08b8f2b09366e97896a4a8cf9ff3bb4d54380 and https://github.com/rust-lang/rustlings/commit/114b54cbdb977234b39e5f180d937c14c78bb8b2#diff-ce1c232ff0ddaff909351bb84cb5bff423b5b9e04f21fd4db7ffe443e598e174) removed the mathematical complexity, and I feel this addition is a needed change to further streamline the exercise.
> fix(structs3.rs): assigned value to cents_per_gram in test

- exercises/option/README.md
- exercises/option/option1.rs
Added further information for *option/option2.rs* since `if let` and `while let` were not covered by the links.
> docs(option): improve further information if let and while let

- README.md
- install.sh
Just tried installing Rustlings using the `install.sh` script on a fresh Ubuntu install and I forgot to install `build-essential` so it failed once cargo started trying to compile. This commit adds a check to the script for `cc` as well as a note to `README.md`.
I'm not on an OSX system right now, but iirc `cc` is what the Xcode CLI tools uses, as well so it should work across both platforms. Not sure about Windows.
If you would prefer that I make a PR with only the `README.md` change, I'm happy to do that.
> Add hints on how to get gcc installed

- exercises/move_semantics/move_semantics6.rs
- info.toml
Could help to learn the difference between ownership and borrowed value in arguments of function and why use one or the other depending of the situation.
> feat: Add move_semantics6.rs exercise (importance of & in arguments of function)

- exercises/move_semantics/mod.rs
Recent exercise `move_semantics6` was not referenced in its `mod.rs`.
> fix(move_semantics) : add move_semantics6.rs to its mod

- install.sh
When installing rustlings in a directory that contains whitespaces (not common, but possible), `install.sh` fails *improperly*.
The script tries to continue the process even if a command has failed.
My proposal is:
* to protect variables that come from "outside"
* to add `set -euo pipefail` to stop at the first error (error, undefined variable or pipe failure)
> fix(install): protect path with whitespaces using quotes

- exercises/move_semantics/move_semantics2.rs
In `move_semantics2` you can get it to compile and pass by simply moving `vec1` below the first `println!` function, so this is to tell people to avoid doing that.
> Add comment about avoiding "cheesing" a solution

- exercises/error_handling/errors6.rs
Although marked as 'TODO', three tests pass without any implementation because the correct answer code already exists.
> fix(errors6.rs): remove one answer code

- exercises/conversions/using_as.rs
`fold()` works fine here but `sum()` is much easier to understand for a beginner.
> refactor(using_as): improve readability by using sum() instead of fold()

- info.toml
The hint for `move_semantics5` refers to "the range in which each
mutable reference is in vogue". Unless this is a deliberate
introduction of "vogue" (an admittedly-useful term because "scope"
isn't purely lexical, as in many other languages), it may be in error:
I have been unable to find the term used with reference to *Rust*
references.
Thus, I'm suggesting the replacement, in case it's been overlooked.
> docs(move_semantics5): Replace "in vogue" with "in scope" in hint

- README.md
[Git.io deprecation](https://github.blog/changelog/2022-04-25-git-io-deprecation/)
> Effective Friday, April 29, 2022 all links on git.io will stop redirecting. Please update any existing links that make use of the git.io URL service immediately.
- Replace git.io with original URL
> docs: replace git.io link with the original URL

- install.sh
Issue Number: close #985 
Problem Summary: Our `install.sh` has `MinRustVersion` such as 1.56.And bash will have a version check,it will split to array and to check one by one.But there is a cornor case,when user use the same version but has `z` version (x.y.z).The short will out of bound(version=x.y).So i add a `pad right` to ensure the length of them is the same.
https://github.com/rust-lang/rustlings/blob/102a4b92a0c2e98ff4ba9f060850d81b4ebbe42f/install.sh#L73-L99
Add a `pad right` to ensure the length of them is the same to avoid out of bound of array.
```shell
#pad right in short arr
if [[ len1 -gt len2 ]];
then
for ((i = len2; i < len1; i++));
do
v2[$i]=0
done
else
for ((i = len1; i < len2; i++));
do
v1[$i]=0
done
fi
```
> fix(install.sh):fix `rust version` check

- .gitpod.yml
- README.md
Currently, when we open the `ruslings` codebase on `gitpod` vscode, the following error is warning is being thrown and the `rust-lang` vscode extension is not installed:
This PR enables the installation of the official `rust-lang` vscode extension. Furthermore, this PR also updates the `Open in Gitpod` link to have the official button.
> remove deprecated user uploaded extension from .gitpod.yml

- .gitignore
- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
- src/project.rs
This is continuing from #911, as requested I've moved functionality into a subcommand that can be run like `rustings lsp` and added documentation plus added it to the initial welcome message.
This will ensure a good developer experience for newcomers to the Rust ecosystem.
> Add lsp command to fix rust-analyzer

- src/exercise.rs
workaround for this issue https://github.com/rust-lang/rustlings/issues/1022
> change edition to 2021 in exercices.rs

- tests/integration_tests.rs
`run_single_test_success_with_output` and `run_single_test_success_without_output` check the stdout from this test:
https://github.com/rust-lang/rustlings/blob/a02b27975018f69c51147f5f8d9638a5f4e26811/tests/fixture/success/testSuccess.rs#L3
but are missing the final "S" in "PASS".
> fix(run): correct "PAS" in `integration_tests.rs`

- exercises/standard_library_types/box1.rs
`todo!` better matches the exercise's intent than `unimplemented!`
> The difference between `unimplemented!` and `todo!` is that while `todo!` conveys an intent of implementing the functionality later and the message is "not yet implemented", `unimplemented!` makes no such claims. Its message is "not implemented". Also some IDEs will mark `todo!`s.
Furthermore, all other exercise's use `todo!`, so it's also a matter of consistency.
> refactor(box1): prefer todo! over unimplemented!

- exercises/options/options1.rs
Expected result is updated to better showcase the difference between
- a valid result with no ice-creams `Some(0)`, and
- an invalid result `None`.
> feat(options1): update expected result

- info.toml
When I run `rustlings watch`, main.rs panics when trying to read info.toml which is caused by the extra " character on line 748 in the info.toml file. 
edit - realized we would want to keep `"use std::fmt::Display;"` so open to a better fix that the parser will be happy with
> fix: remove extra " typo in info.toml

- exercises/macros/README.md
The README for the macros exercise linked to the discontinued versions of the macros book. The newer version, however, is already linked in the macros4 hint:
https://github.com/rust-lang/rustlings/blob/300cdc27dd0eb06939e187f86dd5833d146339a3/info.toml#L1029-L1041
> fix(macros-readme): update the book link to the more recent version of the book

- exercises/quiz2.rs
Change `to` to `do` so that it reads smoothly without error.
> Fix minor spelling

- exercises/traits/traits5.rs
closes #1088
By adding usages of `some_func` to `main`, as well as having a second Struct which implements the traits, the solution for this exercise is to use traits. Without the usages, the exercise can be solved by substituting `SomeStruct` for `??`.
> fix(traits5): make exercise prefer trait-based solution

- exercises/options/options1.rs
Since rewriting the exercise in commit 06e4fd376586 the print_number function goes unused. Remove it.
> fix(options1): remove unused code

- exercises/standard_library_types/cow1.rs
- info.toml
Adds an exercise for the `Cow` type based off of the official documentation at https://doc.rust-lang.org/std/borrow/enum.Cow.html
> feat: add cow1.rs exercise

- exercises/options/options2.rs
- info.toml
Closes: #1109 
**Note**
The author of #1109 has elaborated on what the exercise lacks, and is comfortable with how the exercise currently is laid out.
**Changelog**
- Remove `main` function
- Make `options2` _test_, not _compile_
> `options2`: Convert the main function into tests

- src/main.rs
- src/run.rs
- tests/integration_tests.rs
Closes: #1031 
**Changelog**
- Add `reset` command
**How to test**
1. `cargo build`
2. Do some changes to a file, for instance `intro2.rs`
3. `cargo run reset intro2`
4. Observe that only `exercises/intro/intro2.rs` was stashed
> Add reset command for a given filename

- info.toml
Seems like it's the first place, where `std` is introduced in Rustlings, and it's a good place to facilitate docs discovery for user. As _the book_ seems to have no Rustlings-sized solutions for this exercise.
> Add link to `std` in `strings3` hint

- info.toml
step 2.1 was renamed to step 3, and step 3 was renamed to step 4 in `iterators1.rs` (0bd7a0631a17a9d69af5746795a30efc9cf64e6e), but the hint was not updated accordingly.
> improve hint for iterators1

- info.toml
It didn't work without last character
> Correct a link in `threads1` `hint`

- exercises/structs/structs3.rs
There is only one condition to test get_fees. 
Returning 4500 would get a green test.
A additional Test with double price per gram would make things harder.
> additional test for fees

- .gitignore
- .vscode/extensions.json
VSCode supports recommending extensions through a file : https://code.visualstudio.com/docs/editor/extension-marketplace#_workspace-recommended-extensions
This is what the prompt looks like:    
I think this allows us to help newcomers set-up their tooling easily, and that the recommended extension ([rust-analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer)) is pretty consensual.
Usually I am in favour of leaving IDE config files out of repositories, but I think this is a good fit for rustlings.
Let me know your thoughts!
> feat: Add VSCode extension recommendation

- exercises/options/options1.rs
This PR fixes a corner case in the instructions for the options1 exercise which conflicts with the ordinary understanding of 24-hour time. The corner case was not checked for by any of the asserts in the exercise, so I was unable to find a current issue. The problem is that 24 is not a valid hour for 24-hour time, so None should be returned when `time_of_day > 23`, not when `time_of_day > 24` as in the main branch. Additionally, I added an extra (and redundant) explanation that “12 AM is a value of 0” in order to hopefully hint that the 24 hours in “24-hour time” are 0-23.
I considered and abandoned (for this commit) adding additional `assert_eq!` invocations for when time_of_day is 0 or 24.
> docs(options1): fix and clarify 24 hour time instruction

- src/exercise.rs
- src/main.rs
- src/run.rs
- src/verify.rs
This lint should also be applied to the excersies, but I am not certain how to run it for all non-crate individual files.
To re-run:
```
rustup run nightly cargo clippy --fix -- -A clippy::all -W clippy::uninlined_format_args
```
> Apply uninlined-format-args clippy lint

- exercises/threads/threads2.rs
- exercises/threads/threads3.rs
The [Rust book](https://doc.rust-lang.org/book/ch15-04-rc.html?highlight=clone()#cloning-an-rc-increases-the-reference-count) recommends `Arc::clone` over just `.clone()` to highlight the fact that this doesn't perform a deep copy the way other types' implementations do.
> style: explicitly use Arc::clone

- exercises/conversions/as_ref_mut.rs
This change makes it possible to finish the last exercise without touching the test code, seems like an overlook when code was added since there's nothing in the hints about this extension neither.
It's virtually impossible to write a the `num_sq` function to take the Box since it doesn't implement `MulAssign`.
> fix: Add a deref in the test code

- exercises/conversions/as_ref_mut.rs
Revert the addition of a deref in PR #1192 by me, which should not be there.
Apologies for the inconvenience caused.
Also remove me from the contributors list if neccessary as this was my only contribution.
> fix: Revert deref change

- exercises/macros/README.md
I recently created a series of exercises focused on writing fully featured Macros; since rustlings doesn't have an extensive course
on this. I considered merging them into rustlings (and I'd be happy to look at doing so); but since they focus heavily on using cargo-expand to show what the macros are; I didn't want to force rustlings to have a dependency on nightly.
Hopefully this resource can help your users out too!
> feat(macros-readme): Add link to MacroKata

- exercises/error_handling/errors5.rs
- exercises/error_handling/errors6.rs
Quick formatting fix using `rustfmt` on `errors5.rs` and `errors6.rs`.
> style: format errors5 & errors6 with rustfmt

- info.toml
- Removed reference to panic! since this exercise has been updated so that this step is no longer required https://github.com/rust-lang/rustlings/issues/685
- Updated hint for `get_fees` to use the name of the function to be implemented rather than the name of the test, and to make the hint a bit more helpful
> fix: Update structs3 hint

- exercises/hashmaps/hashmaps3.rs
Small typo fix in `exercises/hashmaps/hashmaps3.rs`.
> fix(hashmaps3): fix typo in todo hint

- exercises/enums/enums2.rs
Remove unneeded level or indirection when calling `println!`. Since the method parameter is of type `&self`, it's already a borrow.
> fix: Remove superfluous &self indirection

- info.toml
It's a bit disturbing to see _rust_ in text when referring to the Rust language.
> chore: "rust" -> "Rust" in exercise hints

- exercises/enums/enums3.rs
The circumstances surrounding tuples and additional parentheses are in regard to passing an argument to a function. Otherwise, I could not find any reference stating that extra parentheses indicate a tuple.
If I create a tuple such as let tup = (('a',)) I receive the following warning:
unnecessary parentheses around assigned value '#[warn(unused_parens)] on by default'
Furthermore, if I made an attempt to indicate a tuple with a single element by doing double parentheses
let tup = (('a'))
the rustfmt will automatically remove the extra parentheses and assume I meant to indicate a char type. Similar to Python, the comma after the lone element is what will indicate the value being a tuple. ('a',)
> chore: update enums3.rs addressing extra parentheses usage with tuples

- flake.nix
- src/project.rs
In addition to the issue described in #1292 it also sets correctly RUST_SRC_PATH and patches `rustlings lsp` to make use of it if available. Otherwise the path for `sysroot_src` is computed wrongly making `rust-analyzer` fail.
> fix nix environment

- info.toml
changed `https://doc.rust-lang.org/std/vec/struct.Vec.html.` 
to `https://doc.rust-lang.org/std/vec/struct.Vec.html`
> minor changes to hint

- src/verify.rs
Noticed that the percent of exercises completed did not update in the progress bar when the sub-commands verify or watch were run. The percentage would update when working through the exercises - when the loop section section of the watch routine in src/main.rs had been entered.
Fixed the verify function in src/verify.rs so that the percentage would update by counting the number of exercises verified. A cleaner solution would be to use the _percent_ key in the progress bar template (https://docs.rs/indicatif/latest/indicatif/index.html#templates) to implicitly change the progress percentage instead of explicitly manipulating the message to display the progress percentage. The _percent_ key, however, does not show any digits after the decimal point (maybe another feature to implement …
> fix(verify): progress bar percent now updates with the number of files verified

- exercises/smart_pointers/rc1.rs
Thanks for this awesome project!
I found a minor issue that missed a blank line, which causes the prompt incorrect like below:
```rust
You can keep working on this exercise,
or jump into the next one by removing the `I AM NOT DONE` comment:
6 |  // Make this code compile by using the proper Rc primitives to express that the sun has multiple owners.
7 |  
8 |  // I AM NOT DONE
9 |  use std::rc::Rc;
```
> chore: fix prompt error for exercise #80 (rc1.rs)

- src/exercise.rs
The edition args of `rustc` is set to 2018 by default. While rustling generate `rust-project.json` [with edition setting to 2021](https://github.com/rust-lang/rustlings/blob/main/src/project.rs#L46). It may cause [some problems](https://users.rust-lang.org/t/rust-analyzer-and-cargo-give-different-type-inferences-for-the-same-code/88790).
> Fix the problem of different edition between rustc and rust-analyzer

- install.sh
Hello!
I've made two changes to the install script:
- change the implementation of `vercomp` to stop it looping beyond the end of the version numbers
- increased `MinRustVersion` from `1.56` to `1.58`, as this was the lowest version of rustc that compiled rustlings without errors
When I first tried to use the install script, I got this error:
```
bash: line 105: v1[$i]: unbound variable
```
This was because my current version of rustc was 1.56.0, the same as `MinRustVersion`. I think this was causing the loop at https://github.com/rust-lang/rustlings/blob/0ea42f60bd559dd7f99c2d7019898505488f7734/install.sh#L102 to reach `max_len` (3 in this case), which was outside the range of array indices (0..2). **Please note that I suck at bash so I could be wrong**. 
Then I got errors while building …
> Fix `bash: line 105: v1[$i]: unbound variable` in install script

- exercises/threads/threads1.rs
- info.toml
Attempts to close #1298
- program verifies that threads have been joined by checking if `results` vector has been filled
- solution now involves recognizing that `JoinHandle::join` returns a `Result`, unpacking it, and adding the value to a vector
> fix(threads1): make program panic if threads are not joined

- exercises/smart_pointers/cow1.rs
- info.toml
Following the discussion in #1195 this is the best I could come up with. The issue for me (and apparently a few other learners) was that the code needed to complete the exercise was not _missing_, but was rather there but wrong.
In the end, what made the difference between this exercise and others (for me) was that in this exercise I was supposed to learn what to *expect* of an output. So I think it makes sense here to let the learner modify the tests and not the code itself.
Side note: once [`assert_match!`](https://doc.rust-lang.org/std/assert_matches/macro.assert_matches.html) becomes stable I'd like to integrate it here just to expose the learner to it and because it makes the tests much clearer to read. This is how I had written it before realizing that probably most people don't use …
> refactor(cow1):  replace main with tests

- README.md
The truncated lines from the uninstall instructions are gratuitous. Removing them makes the section more concise and clear.
> Removed verbose instructions from the uninstall section

- exercises/error_handling/errors5.rs
I had to re-read the edited line a few times to understand that "..." and "???" refer to the same thing. I think, applying this change will keep the notation consistent across the comment and the body of the exercise, since `main`'s signature is initially defined with question marks as well.
```rust
fn main() -> Result<(), Box<dyn ???>>
```
> fix: unify undisclosed type notation in errors5.rs

- exercises/smart_pointers/arc1.rs
As discussed in https://github.com/rust-lang/rustlings/pull/968, it is better to avoir implicit stuff in tutorials. This PR thus replaces an implicit dereference with an explicit type.
> refactor(arc1): improve readability by avoiding implicit dereference

- exercises/macros/macros4.rs
The `macros4.rs` challenge can automatically be solved by rustfmt without the user noticing.
Adding `#[rustfmt::skip]` above the `macro_rules!` line fixes this issue.
> fix(macros4.rs): Add rustfmt::skip to prevent auto-fix.

- install.sh
The rustlings installation script threw me an error:
```
curl -L https://raw.githubusercontent.com/rust-lang/rustlings/main/install.sh | bash
```
>  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                       Dload  Upload   Total   Spent    Left  Speed
> 100  4597  100  4597    0     0  13119      0 --:--:-- --:--:-- --:--:-- 13286
> Let's get you set up with Rustlings!
> Checking requirements...
> SUCCESS: Git is installed
> SUCCESS: cc is installed
> SUCCESS: rustup is installed
> SUCCESS: Rust is installed
> SUCCESS: Cargo is installed
> SUCCESS: Rust is up to date
> Cloning Rustlings at rustlings/...
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> KeyError: 'tag_name'
After investigating, I …
> Better error message when failing

- Cargo.lock
I encountered the same issue as #1430 by trying to launch rustlings with nix. I'm using Apple Silicon that might be the reason, simple `cargo update` helped. Probably the rustling version update is required to account for the environment update, right? 
But the core issue seems to be that nix configuration should be in sync with cargo, which breaks the entire idea of nix. I would be glad to help if you think this is something worth doing
> cargo update to resolve #1430

- exercises/lifetimes/README.md
Much like Macrokata, Lifetimekata is a project we've been using to teach lifetimes at the University of New South Wales. 
I've added it here because I think it'll be useful for people who have finished your lifetimes exercises.
> feat(lifetimekata): Add info about Lifetimekata project

- exercises/lifetimes/README.md
Changed the order in which the references are presented. Now first reference is "Lifetimes (in Rust By Example)", showing a very brief introduction to the concept of lifetimes in references. Then, "Validating References with Lifetimes", where the whole concept is explained in full details.
The previous order didn't make sense as the second reference didn't contain anything new.
Also, first PR ever. Is there something missing? Should I use another name for my branch (something like "issue#")?
> change order of references in README.md

- info.toml
This order is better if one's working through the exercises in the sequence of "The Book" where lifetimes is covered in Ch. 10.3 whereas tests are covered in Ch. 11.
> fix: move lifetimes above tests in recommended order

- exercises/iterators/iterators5.rs
Tiny tweak: I changed the sentence that referenced the imperative implementation in iterators5.rs.
The imperative implementation was already removed and replaced with `todo!()`, so the reference could be confusing.
> docs: clarify instructions on iterators5.rs

- info.toml
after #144, the signature doesn't need changing anymore
> chore: update move_semantics4.rs' hint

- src/main.rs
As the example added to `help` implies, this makes it easy to do things like explain a compiler warning without having to open a new terminal.
> feat: Add "!" command to `rustlings watch`

- exercises/move_semantics/move_semantics2.rs
Commit fef8314 added three lines of comments, which left the line numbers expected to stay unchanged mentioned on line 2 out of date.
> fix(move_semantics2): fix line number comment

- exercises/smart_pointers/cow1.rs
I was initially confused by this comment describing Cow when owned without mutation. I changed it slightly to clarify why Cow maintains ownership a little better
> chore: clarified cow owned_no_mutation comments

- exercises/options/options3.rs
Closes #1503
I searched through the other `match` statements and did not really find any similar situations, so I only changed this file.
> fix(options3): panic when not matching to avoid false positives

- info.toml
Add link to get more information
```https://doc.rust-lang.org/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html#re-exporting-names-with-pub-use```
> modules2.rs: add more information to hint

- exercises/options/options2.rs
The existing test can be solved with the following:
```rs
while let Some(integer) = optional_integers.pop() {
assert_eq!(integer.unwrap(), range);
```
Similarly with `expect(...)`, `unwrap_or(0)`, `unwrap_or_default()`, etc. However, none of these solutions use the learning point of stacking `Option<T>`s.
The updated test can _only_ be solved by stacking `Option<T>`s:
```rs
while let Some(Some(integer)) = optional_integers.pop() {
assert_eq!(integer, cursor);
```
With the updated test, using `unwrap` or `expect` will panic when it hits the `None` value, and using `unwrap_or` or `unwrap_or_default` will cause the final `assert_eq!(cursor, 0)`  to panic.
> feat(options2): better test for layered_option

- exercises/iterators/iterators5.rs
Firstly, I want to say that I've been really impressed with rustlings. This is my first foray into Rust programming and I've really enjoyed running through the exercises over the last few days so I wanted to contribute something in return.
Based on [this issue](https://github.com/rust-lang/rustlings/issues/1387), I've added some more detailed tests to the iterators5 exercise as I think the author has raised a valid point.
I've added new tests to validate that the output is correct for all progress types and I've also updated the tests that compare against the equivalent functions (that use for loops) to ensure that the output is the same for each type. 
Please let me know if there are any edits you would like me to make. Thanks!
> fix: Added some extra tests to validate iterators5 solution

- info.toml
The hint currently tells you to add `return 0` to the `count_collection_iterator` to make it compile. This is not necessary because the `todo!()` macro is used.
> feat(iterators5): remove outdated part of hint

- .github/workflows/rust.yml
This PR prevents issues like #1430 from reoccurring.
---
[Issue #1430](https://github.com/rust-lang/rustlings/issues/1430) was caused by `Cargo.lock` being out of sync with `Cargo.toml`; in [the commit](https://github.com/rust-lang/rustlings/tree/9acefe8b3a2bed6e23dc31e9c1d5e9c5f6ab7596) preceding the merge of [PR #1435](https://github.com/rust-lang/rustlings/pull/1435), [`Cargo.toml`](https://github.com/rust-lang/rustlings/blob/568767601427cccf11ef8ea0dd20ad1ac0dbee1e/Cargo.toml#L3) had rustlings at version 5.4.1 and [`Cargo.lock`](https://github.com/rust-lang/rustlings/blob/568767601427cccf11ef8ea0dd20ad1ac0dbee1e/Cargo.lock#L462) had rustlings at 5.4.0.
Under "normal" (non-`nix`) conditions, unless the `--frozen` or `--locked` flags are passed to `cargo` calls, `cargo` will silently …
> chore(ci): add action step to check if lockfile is synced

- exercises/enums/enums3.rs
closes #1548
I've changed the exercie slightly so that all code paths are tested. Even the Echo code path asserts the message. In my issue I managed to pass the test without implementing anything for the `Message::Echo` match logic.
```rust
match message {
Message::Move(point) => {self.move_position(point)},
Message::Echo(string) => {}, // I pass the exercie without implementing this.
Message::ChangeColor(x, y, z) => { self.change_color((x, y, z))},
Message::Quit => { self.quit() },
}
```
> fix(enums3): add test for message

- exercises/hashmaps/hashmaps3.rs
Field name of the Team struct isn't needed. Removed this struct and updated the comment above the struct to reflect this change
> fix: update hashmaps3.rs

- exercises/hashmaps/hashmaps2.rs
The existing test functions only check if a kind of fruit exists in the hashmap, but not if the amount of fruits is higher than zero. This new test function solves this.
> feat: added test function to hashmaps2.rs

- info.toml
The variable mentioned in the hint for `vecs2` is (presumably) outdated. I updated the name in the hint to reflect the code of `vecs2`, and tried to adhere to the line length seen throughout the file.
> fix(vecs): rename outdated variable name in hint

- info.toml
Hello @shadows-withal 
I have seen pull request #1544, and I must admit I am somewhat disappointed with the phrase "`element` is each element" as it could be formulated differently. That's why I have decided that the entire sentence should be rewritten from scratch.
Imo for clarity we should try to avoid redundant statements whenever possible.
> chore: update hint for vecs2

- Cargo.lock
Fresh download of `rustlings` currently does not build on nightly Rust:
```none
$> git clone https://github.com/rust-lang/rustlings.git
...
$> cd rustlings/
$> rustc --version
rustc 1.73.0-nightly (7bd81ee19 2023-07-13)
$> cargo --version
cargo 1.73.0-nightly (694a57956 2023-07-11)
$> git checkout main
...
$> cargo clean
$> cargo build
Compiling libc v0.2.140
Compiling proc-macro2 v1.0.53
// ...
Compiling regex-syntax v0.6.29
error[E0635]: unknown feature `proc_macro_span_shrink`
--> /home/nicholas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.53/src/lib.rs:92:30
|
92 |     feature(proc_macro_span, proc_macro_span_shrink)
|                              ^^^^^^^^^^^^^^^^^^^^^^
Compiling bitflags v1.3.2
Compiling same-file v1.0.6
For more information about this error, …
```
> fix: building rustlings on nightly

- exercises/error_handling/errors4.rs
I was a bit confused about this comment since I thought there was supposed to be something more than the Ok value there. But the problem is that the Ok value is always returned. Switching only -> always to signify that better.
> chore(errors4): improved comment

- exercises/error_handling/errors2.rs
Fixes a trivial comment that references `parse` function, but that function does not exist. It exists as `total_cost`
> Fix comment in errors2

- exercises/error_handling/errors1.rs
The way this description war written implied that similar but else than `Result` should be used. Which is not correct according to hint and provided tests. I have updated it to say that something like `Option` can be used to solve the exercise. 
If the intention was to mention `Result` explicitly to make the exercise easier, then I would phrase it like this:
> Rust has a similar construct to `Option` - `Result`, that can be used to express error conditions.
> fix(errors1): change Result to Option in exersise description

- info.toml
First, I wanted to fix these line numbers that are not correct anymore.
But to avoid having this in the future, I just removed every line number in the hints and described the line instead.
> Avoid line numbers in hints

- exercises/structs/structs3.rs
I think that we should teach using the fitting type. Using `i32` and then matching if the value is <= 0 is a bad practice. Therefore, I used `u32` instead. We could also check if `u32` is zero instead of `< 10`. That would also be fine. But the point is that there is no reason that either the price or the weigth are negative (unless we talk about antimatter, but I don't think that you would want to ship that 🤣)
I also added a message about the panic on input validation to make it clear that this is not how one should handle errors in Rust. But we didn't get to `Result` yet.
Ignore the typo in the branch name :P
> Use u32 instead of i32

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/integration_tests.rs
The arguments from the PR https://github.com/rust-lang/rustlings/pull/715 that replaced Clap with argh are not valid anymore.
Currently, this branch has only 7 more dependencies. The difference in compilation time is not significant.
Compiling the `main` branch:
```console
$ hyperfine -- "rm -r target && cargo b -r"
Benchmark 1: rm -r target && cargo b -r
Time (mean ± σ):     11.496 s ±  0.206 s    [User: 89.523 s, System: 5.787 s]
Range (min … max):   11.161 s … 11.822 s    10 runs
```
Compiling this `clap` branch:
```console
$ hyperfine -- "rm -r target && cargo b -r"
Benchmark 1: rm -r target && cargo b -r
Time (mean ± σ):     13.415 s ±  0.290 s    [User: 115.880 s, System: 6.849 s]
Range (min … max):   12.859 s … 13.865 s    10 runs
```
The benchmarks show that the compilation time …
> Port to Clap

- flake.nix
The integration test `reset_single_exercise` depends on Git...
Fixes the last error mentioned in #1652.
Many thanks to people at https://matrix.to/#/!bohcSYPVoePqBDWlvE:hackint.org's weekly mumble session for figuring out the root cause of this problem =)
> fix(nix/tests): Add `git` to Nix's rust build/test sandbox

- flake.nix
So that:
- `nix build .#`, and
- `nix run .#` both work.
> feat(flake): Add defaults to commands in flake

- info.toml
the previous text does not appear in the provided link (https://doc.rust-lang.org/book/ch16-03-shared-state.html#atomic-reference-counting-with-arct).
> info.toml: update threads2 text.

- info.toml
Hi there, first day at rustlings, enjoying the learning system. Thanks!!
This is a small PR to fix what (in my opinion) is a bit confusing hint.
Current hint:
>  use the starting and ending indices of the items in the Array
Problem:
In the documentation it's explained that is ending `PLUS ONE` (which is also expected I guess). I tried the hint literally in the excercise and it wasn't working.
I hope this is useful :)
> fix(primitives-4.rs): update hint so it's less confusing

- info.toml
Resolves a side-effect of PR #1535. In making the boilerplate consistent, [several new lines](https://github.com/rust-lang/rustlings/commit/7eef5d15eef780f93e22b1b4e0185f7708219ea0#diff-0eb1285ec18690b4824b04771d7b390176ef133a218d6b45c614e947fe2b3b0f) were added - misaligning the hint.
The new offending line is [line 12](https://github.com/rust-lang/rustlings/blob/main/exercises/strings/strings2.rs#L12). That being said, it might be more stable to just remove the line reference altogether.
> _There is a way to add one character ~~to line 12~~, though, that will coerce the `String` into a string slice._
> chore: update line reference in strings2 hint

- exercises/enums/enums3.rs
Otherwise it won't actually test the change of state.message and it would fail to check if the user missed changing state.message
This happened to me as I had a catch-all line in `match`
> fix(enums3): modify message string in test

- exercises/iterators/iterators1.rs
- exercises/move_semantics/move_semantics3.rs
- exercises/move_semantics/move_semantics5.rs
- exercises/smart_pointers/rc1.rs
- exercises/threads/threads3.rs
- info.toml
Converted all exercises having assertions to test mode.
I am not really sure about all implications of this conversion. Please review it first. You might think that some of them should have both a main function and a test.
Should the function names be changed? `main` is not a good test function name. I can use other names if you want.
> Convert exercises with assertions to tests

- exercises/smart_pointers/cow1.rs
Following the discussion on #1195 a [commit](https://github.com/rust-lang/rustlings/commit/720f33eee642eafab3c03bc7caed5f8690b481e8) added `.to_mut()` to the last `Cow::from(slice)` call. However that doesn't compile (or make sense for that matter, since it returns the mutable inner type). I think from reading the comments in [this commit](https://github.com/ComixHe/rustlings/commit/a75b94105ef220e07b3920a3c762ed1d9959bc3a) that the comments are talking about the `.to_mut()` call in the `abs_all()` function and the commit that added the call just misinterpreted what the comments say. At any rate, this makes it compile.
> Fix compiler error and clarify instructions

- exercises/primitive_types/primitive_types3.rs
The current implementation of `primitive_types3` allows an array of any length to compile, hence invalidating the requirement in the top comment.
This PR adds a panic to the else clause so that it won't compile if the array is too small.
> Make `primitive_types3` require at least 100 elements

- exercises/clippy/clippy3.rs
- exercises/primitive_types/primitive_types1.rs
- exercises/primitive_types/primitive_types2.rs
three files still point to a hint that isn't there.
> remove hint comments when no hint exists

- exercises/conversions/as_ref_mut.rs
> fix: test name typo

- exercises/enums/enums3.rs
`enums3` was not properly formatted.
In VSCode with FormatOnSave, these lines change as soon as you save, hence showing differences before you even start working on the exercise, which might cause confusion.
> Fixed formatting of `enums3` with rustfmt

- install.ps1
- install.sh
Since #1633 porting to Clap, min Rust version requirement changes.
> fix(installation): bump MinRustVersion to 1.70

- src/exercise.rs
Previously, this would just say "missing file". Now it shows the path of the file that was missing.
This would have made https://github.com/rust-lang/rustlings/issues/1689 easier to debug.
> Give a more helpful error when a file is missing

- exercises/error_handling/errors2.rs
- info.toml
chore(errors1): fix grammar typo in hint for exercise errors1
This commit corrects a grammar typo in the hint of the errors1 exercise, changing from:
"`Ok` and `Err` are one of the variants of `Result`,"
to:
"`Ok` and `Err` are the two variants of `Result`,"
---
chore(errors2): minor description wording change in errors2 exercise
This commit makes a minor change in the wording of the description of the errors2 exercise to avoid potential confusion, changing:
"A player of the game will type in how many items they want to buy, and the `total_cost` function will calculate the total cost of the tokens."
to
"A player of the game will type in how many items they want to buy, and the `total_cost` function will calculate the total cost of the items."
> chore(errors): fix grammar typo and wording in errors exercises

- src/exercise.rs
... to reflect the changes to the exercise directory names.
The path `exercises/clippy` replaced with `exercises/22_clippy`.
closes #1726
> fix(watch): update the CLIPPY_CARGO_TOML_PATH

- README.md
Currently, the windows installation instructions download a script from the URL `ps1.rustlings.cool`. This URL isn't detected as a URL in some cases, which means that PowerShell tries to load the data from a local file called `ps1.rustlings.cool`.
This was breaking my install, and adding the `https://` fixed it.
> docs: fix windows installation instructions

- exercises/00_intro/intro2.rs
- info.toml
I think intro2 is too difficult to be the very first real exercise, and we're scaring away some students unnecessarily. 
**TL;DR: I've made a tweak to intro2 to cause a much friendlier compiler error.**
The existing error for `intro2` is more difficult to understand compared with subsequent exercises. That's not right, the Rustlings exercises are otherwise in ascending order of difficulty. The first one should be the easiest!
The existing intro2 error is:
```rust
error: 1 positional argument in format string, but no arguments were given
--> exercises/intro/intro2.rs:11:21
println!("Hello {}!");
^^
error: aborting due to previous error
```
This is *terrifying* as an error! There's not even a hint or compiler help to aid us! Even existing programmers coming from other languages might be …
> fix(intro2): Changed intro2 to be a name error, not a format string error

- src/main.rs
Fix #1691 
The saved exercise was counted twice, the second time was inside the verify function with `bar.inc(1)`.
Now the count after saving is consistent with the count at startup.
Please let me know if there's any doubt about this fix.
> Fix progress bar

- README.md
Continuing https://github.com/rust-lang/rustlings/pull/1738
> Add CodeCrafters to `Continuing On`

- README.md
This reverts commit dad22169849a4d16d6a74c69a45017dab07677ff.
Revert what was done in https://github.com/rust-lang/rustlings/pull/1760
See reasons here, https://github.com/rust-lang/rustlings/pull/1760#issuecomment-1806950184
> Revert "Add CodeCrafters"

- Cargo.lock
- Cargo.toml
- src/main.rs
This updates `notify` to v6 and uses `notify-debouncer-mini` for event debouncing. 
**Please Note:** `notify-debouncer-mini` does NOT distinguish different event kinds but also has fewer dependencies than `notify-debouncer-full`.
I don't think this is a problem in this case, but please let me know if you prefer the version where event kinds are explicitly checked, then I will happily update this PR.
PS: I think one could think about moving the event handling to a separate function, as the watch function is getting a bit complex. For easier review I tried not to do too much changes to the structure. 
So I can do the refactoring in a follow up PR or include it in this one if you prefer it. 
closes #1640
> Update `notify` dependency to v6

- src/main.rs
A few notes besides what is said in the commit messages:
- I haven't tested the color thing on Windows. Testing would be appreciated.
- I am undoing a change that was apparently done by clippy. When I re-run clippy, the change doesn't reappear, but more testing would be appreciated.
> Fe-nish line rendering improvements

- exercises/22_clippy/clippy1.rs
Not sure if I should use `Clippy` or `clippy` though 🤔...
> docs: reword `clippy1` exercise to be more readable

- .gitattributes
Use gitattributes file to ensure script files have LF line endings. This solves a problem for users who wish to use DevContainers on Windows machines and the file has been cloned from the repository with CRLF line endings.
> fix: Ensure scripts have LF line endings

- info.toml
The hint says that `u32` would be more fitting for the prices. But this is only true for the original price and thus as an extension the parameters of the functions, not the type of the return value of `sale_prince`, as this could be negative for `original_price` values between 0 and 10 (specifically it will be negative for the input values of 1, 2, 4, 6 and 8).
Code for the exercise:
```rust
fn main() {
let original_price = 51;
println!("Your sale price is {}", sale_price(original_price));
}
fn sale_price(price: i32) -> i32 {
if is_even(price) {
price - 10
} else {
price - 3
}
}
fn is_even(num: i32) -> bool {
num % 2 == 0
}
```
PS. I know this might be pedantic and certainly will be very far down on the list of priorities, but I have stumbled over this hint multiple times, and the first …
> Clarified hint text

- info.toml
primitive types 4 hint:
areference -> a reference
> chore: minor typo fix

- exercises/11_hashmaps/hashmaps3.rs
I struggled with this exercise and didn't understand that it was looking for a summary of goals scored/conceded per team, instead of per match.
My goal here is just to clarify the language, essentially saying "the total number of goals the team scored" to indicate that we are looking for a sum.
Updated the exercise description to clarify this point.
Relates loosely to closed issue https://github.com/rust-lang/rustlings/issues/1361
> Clarify language in hashmap3.rs (sum vs per match)

- install.sh
The install.sh script didn't work for me, after I changed this locally it worked. URL needs to end in .git
> Fix(Installation) Added .git to end of Repo's https URL

- exercises/06_move_semantics/move_semantics2.rs
- exercises/06_move_semantics/move_semantics3.rs
- exercises/06_move_semantics/move_semantics4.rs
Eliminated unused mutability by reverting the variable vec1 to an immutable state.
The introduction of `mut` in the [initial commit](https://github.com/rust-lang/rustlings/commit/c859550e6ce35bf9923a930aecb80cc83c8f6dff) was essential, but [subsequent changes](https://github.com/rust-lang/rustlings/commit/51e237d5f97610294798710ef8ba5349c2fd50c7) have made mutability unnecessary.
This refinement streamlines the code by acknowledging that the variable no longer necessitates mutability. The adjustment not only improves code clarity and maintainability but also eliminates the `variable does not need to be mutable` warning, enhancing the overall code quality.
> Cleaned Up Unused Mutability

- exercises/03_if/if1.rs
Added a clarifying comment in the `if/if1.rs bigger` function to explicitly mention the behavior when both input numbers are equal.
> docs: Added comment for handling equal numbers in if/if1.rs `bigger` function

- src/verify.rs
I guess that the issue with the final line not being added when executing rustlings verify is due to a buffering problem. To flush the buffer, I added a println statement, and in my environment, it becomes expected stdout.
fix #1898
> show stdout of the final line

- exercises/20_threads/threads3.rs
`Arc` is not needed since a partial move into the threads is possible.
> Remove unneeded Arc

- Cargo.lock
- Cargo.toml
- src/main.rs
This tiny change caused about 2.4x speedup with the `list` command. It is just the command that I done the benchmark with, but it should affect all commands since this rustc check is done in the main function before running any command.
> Use `which` instead of running `rustc --version`

- Cargo.lock
- Cargo.toml
- src/main.rs
I replaced the `toml` crate with `toml_edit`. The `toml` crate uses `toml_edit` under the hood anyway (see https://epage.github.io/blog/2023/01/toml-vs-toml-edit by the author of both crates).
There is one change caused by this move: The `display` feature of `toml_edit` is not enabled now which means that we only activate what we use (`serde` and `parse`).
I also made handling the case of `info.toml` not existing in the current directory part of the error handling when trying to read the file. This eliminates a redundant syscall and the usage of `unwrap`.
> Reading the `info.toml` file

- Cargo.lock
- Cargo.toml
- src/exercise.rs
- src/main.rs
- src/verify.rs
I started some optimizations :D
I optimized the `list` command. That involved the optimization of the `state` method which checks whether an exercise is done or not.
The most important changes are:
1. Instead of reading the whole file to look for the "I AM NOT DONE" comment, iterate over lines with a `BufReader`.
2. Replaced regex with the `winnow` parser.
There is one difference to the old regex: Instead of allowing multiple spaces between the words of the comment (e.g. "I  AM   NOT     DONE"), I now only allow one space but the comment is caseless. So "I am not done" now also works.
This is not a limitation of `winnow`, I just found it useful. Because during my course, some wanted to add the comment back to experiment a bit, but they had to copy the comment instead of just being able to …
> Optimizations 1

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/project.rs
The public API of `RustAnalyzerProject` was sub-optimal because `new` constructed an invalid state of the type that is then filled by two other public methods to get to a valid state.
All what is needed to be exposed from the module is one function which writes the file.
Instead of walking the `exercises` directory, I just used the exercise paths from the `info.toml` file and removed the `glob` dependency.
I also avoided allocations here and there :P
I added `anyhow` as the start of doing proper error reporting instead of using `unwrap`, `expect` or printing and exiting with `std::process::exit`.
> Rewrite `project.rs`

- exercises/README.md
Hi!
It looks like the "Exercise to Book Chapter" table in `exercises/README.md` does not have up to date sorting order in relation with the exercises order. This PR is simply sorting it.
> docs: sort exercise to book chapter mapping by exercise

- exercises/23_conversions/from_str.rs
The advice tell us how to return as String error message. Unless I missed something, we can't even return a String error message in this exercise (we have to return a ParsePersonError), so this advice is more confusing than anything and should better be removed.
> Remove confusing aside in 23_conversions/from_str.rs

- .gitignore
The renaming of the folder requires renaming the gitignore reference as well.
> Fix gitignore for clippy exercise

- exercises/07_structs/structs3.rs
- exercises/11_hashmaps/hashmaps1.rs
when i use rustRover, and there is a grammar error says "Use a comma before 'and' if it connects two independent clauses (unless they are closely connected and short). ".
So add a comma in structs3.rs file will solve this error.
> docs : add a comma in structs3.rs file 

- info.toml
This pull request consist of one commit which changes the format of the hints in the exercises 4 and 5 of traits.
In short, it changes the "<" to "[" like this:
``` toml
hint = """
"Instead of using concrete types as parameters you can use traits. Try replacing 
the '??' with 'impl [what goes here?]
See the documentation at: https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters
"""
```
The reasoning for changing "<" is that right before you learn about using generics. So one could think that the solution to the exercises is by using generics.
> Change hints of exercises traits4 and traits5 for a better learning experience

- info.toml
The hint in `move_semantics1.rs` was not consistent with what was given by the compiler. Rustc gave 
```
error[E0596]: cannot borrow `vec` as mutable, as it is not declared as mutable
``` 
and this was changed in info.toml.
Thanks
> chore: update error message to error message given by rustc (error[E0596]) in hint

- exercises/11_hashmaps/hashmaps2.rs
This is a redo of PR #1626 which I flaked on. This accounts for the new file structure and the formatting request.
> Fix all_fruits_types_in_basket to fail if all fruit kinds are not  included

- exercises/06_move_semantics/move_semantics5.rs
Part of move_semantics5, `string_uppercase` function takes `&String` and intended solution is to change the argument to `String`. However, the compiler error was leading towards a different solution causing confusion. 
```
error[E0716]: temporary value dropped while borrowed
--> ../exercises/06_move_semantics/move_semantics5.rs:21:13
|
20 | fn string_uppercase(mut data: &String) {
|                               - let's call the lifetime of this reference `'1`
21 |     data = &data.to_uppercase();
|     --------^^^^^^^^^^^^^^^^^^^- temporary value is freed at the end of this statement
|     |       |
|     |       creates a temporary value which is freed while still in use
|     assignment requires that borrow lasts for `'1`
```
This PR fixes #1963 such that the new compiler error leads …
> move_semantics5: change to fix misleading compiler error

- solutions/18_iterators/iterators5.rs
On one hand, nested iterators are somewhat common (container of containers, iterator of containers, container of iterators), so introducing `flatten` could be useful.
On the other hand, `flatten`, `flat_map`, etc. are not mentioned in the Rust book...
> Add alternative solution for iterators5

- exercises/11_hashmaps/hashmaps2.rs
In the instructions for hashmaps2.rs, the last sentence of the include the phrase "these fruits", which refers to fruits that were mentioned two sentences prior.
Having a sentence in between the first sentence in which the fruits were described and a later sentence in which the phrase "these fruits" is used makes this confusing to read, since the phrase "these fruits" does not come immediately after the mention of the fruits that the phrase refers to.
This pull request expands the last sentence to explicitly refer to the fruits being mentioned, in order to add clarity about the requirement of the exercise.
> fix: Add clarification to instructions for hashmaps2.rs

- exercises/13_error_handling/errors5.rs
In errors5.rs, there are two lines of a pattern matching block for which the order is reversed between the exercise file and the solution file. Since these lines are not changed as part of the exercise, this commit updates the exercise to make the order of the lines consistent with the solution, so that users will focus only on the lines that change between the exercise and the solution.
> chore: Update errors5.rs exercise to be consistent with solution

- rustlings-macros/info.toml
In the exercise `iterators2`, one variable was renamed from `c` to `chars`. In this PR I reflected this change within the hints for this exercise. 
This is the related exercise:
https://github.com/rust-lang/rustlings/blob/c793416495b3e015cbd4fb5ea23070aad8611614/exercises/18_iterators/iterators2.rs#L6-L12
> Updated name of variable name in hint

- rustlings-macros/info.toml
enhance string3 exercise' hint
Add a `replace_method` hint; I think it would be more helpful for beginners.
- before
- after
- string3 exercise
```rust
fn trim_me(input: &str) -> &str {
// TODO: Remove whitespace from both ends of a string.
}
fn compose_me(input: &str) -> String {
// TODO: Add " world!" to the string! There are multiple ways to do this.
}
fn replace_me(input: &str) -> String {
// TODO: Replace "cars" in the string with "balloons".
}
```
> doc: enchane string3 exercise hint

- exercises/13_error_handling/errors6.rs
- solutions/13_error_handling/errors6.rs
Exercise errors6.rs prompts the user to add a method named `from_parseint`. This commit changes the method name to the corrected snakecase format, `from_parse_int`.
> chore: Fix snakecase convention in errors6.rs

- exercises/11_hashmaps/hashmaps3.rs
- solutions/11_hashmaps/hashmaps3.rs
In the exercise `hashmap3`, the name of the struct is `Team`, but I thought `TeamScores` would be better since it relates to scores(There are several places in the same file where `score` is used.).
Similarly, I made changes to the solution.
> update struct name in hashmap3

- Cargo.lock
- Cargo.toml
- src/app_state.rs
- src/dev/check.rs
hashbrown is already used in the standard library, but we want the improved performance of the different hash algorithm. Using ahash directly conveys this intent more clearly.
> Replace hashbrown with ahash

- Cargo.lock
- Cargo.toml
- src/init.rs
- tests/integration_tests.rs
- Detect if we are in a cargo project more reliably. (e.g. if `rustlings init` is run in the `src/` directory)
- Refuse to initialize rustlings in a non-workspace cargo project.
- Automatically populate the `workspace.members` field if `rustlings init` is run in a workspace.
This may be considered risky, as there is no guarantee that's what the user wanted to do. However, it is consistent with the behavior of `cargo new`. Also, newcomers to Rust are unlikely to accidentally be in a cargo workspace, as they won't know how to create one in the first place.
The use case for initialization in a workspace is when a workshop organizer wants to use rustlings alongside other exerices and provide a single repository with everything in one place.
> Improve initialization in workspace

- rustlings-macros/info.toml
The example provided in the hint for exercise `primitive_types3` does not work
**ACTUAL HINT**
If you try what the hint suggests, it fails
However, if you update the value to be 100, it works (`10` -> `100`)
> Fix example in 'primitive_types3' hint

- dev-rust-analyzer.toml
- src/init.rs
> Add rust-analyzer.toml file

- exercises/08_enums/enums3.rs
The exercise enums2.rs already contains a task where an identical enum has to be defined.
> Remove redundant enum definition task

- exercises/23_conversions/as_ref_mut.rs
- solutions/23_conversions/as_ref_mut.rs
`.len()` already returns the length in bytes when used on a `String` or a `str`. As this might be counter-intuitive for beginners, I've also added an extra comment. This has the benefit of preparing them to a proper use of `.len()` on a string.
> Do not use `.as_bytes().len()` on strings

- exercises/23_conversions/from_str.rs
Changed the typo "`From`" to "`FromStr"`
The implementation name is `FromStr`, not `From`.
Additionally someone opened an issue about this here: https://github.com/rust-lang/rustlings/issues/2123
> fix: typo in `exercises/23_conversions/from_str.rs` 

- clippy.toml
- src/app_state.rs
- src/main.rs
- src/run.rs
- src/term.rs
- src/watch.rs
- src/watch/state.rs
- src/watch/terminal_event.rs
* Update the state of all the exercises instead of stopping with the first failure (especially given the old code was running all of them anyway, it was just ignoring the result of the later exercises). This allows the user to see all the exercises that needs to be redone instead of having to "fix/see one, run check_all, fix/see another, run check_all, ..."
* Fixed the progress display frozen for a long time if/when the first threads were run after later ones
* Limit the number of threads to the number of CPU cores (avoids spawning 94 cargo instances at the same time, possibly more in the future or in custom exercise sets)
* Show a progress bar instead of an unappealing "Progress: xxx/yyy".
* Add a command to run check all the exercises immediately (useful if they are solved without …
> Improvement to "check all exercises"

- exercises/01_variables/README.md
- exercises/08_enums/README.md
- exercises/13_error_handling/README.md
Very minor issue with consistency of apostrophes in Markdown files. This was probably replaced by a word processor as a smart quote. This change makes them all single quotes.
> Use consistent apostrophes in markdown files

- exercises/12_options/options1.rs
If this is intended for any reason, please ignore this PR.
IDE flags them as typo, and I couldn't resist to submit a PR.
I'm using RustRover, if this ever matters.
> Fix possible typo of `icecream` to `ice cream` on `options1.rs`

- exercises/09_strings/strings3.rs
Technically, this change doesn't directly test for idempotence, as the `fn` is called once instead of being chained. I still believe it adds value, because it can make the challenge "harder" while still being fair.
> [!note]
> The following is just feedback from my recent experience. It can be ignored as "off-topic", but I believe it might be helpful for designing exercises in general.
BTW, when I was solving it, I felt like using `trim` method was "cheating", so I implemented it myself:
```rust
fn trim_me(input: &str) -> &str {
let l = |c| c != ' ';
let start = input.find(l).unwrap_or_default();
// it's easier to let patterns do their job
// than to handle arithmetic overflows manually,
// hence the asymmetry
match input.rfind(l) {
Some(end) => &input[start..=end],
_ => &input[start..], …
```
> test idempotence of `trim_me` in `strings3.rs`

- exercises/13_error_handling/errors4.rs
Makes the "TODO: This function shouldn't always return an `Ok`." in error4 less vague and adds "Read the tests below to clarify what should be returned.".
> Clarify how to find return type of error4
